In [2]:
import pandas as pd

dataset=pd.read_json('/home/hammadali08/Personal/FYP Datasets/News_Category_Dataset_v3.json',lines=True)
dataset=dataset.head(1000)
dataset

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
995,https://www.huffpost.com/entry/china-weighs-ex...,China Weighs Exit From 'Zero COVID' And The Ri...,WORLD NEWS,The change does not appear imminent as the gov...,"Dake Kang and Huizhong Wu, AP",2022-03-18
996,https://www.huffpost.com/entry/russian-missile...,Russian Missiles Hit Near Lviv Airport As Stri...,WORLD NEWS,World leaders have been calling for an investi...,"Cara Anna, AP",2022-03-18
997,https://www.huffpost.com/entry/assad-uae_n_623...,"Syria's Assad Visits UAE, 1st Trip To Arab Cou...",WORLD NEWS,Assad's office said he met with Sheikh Mohamed...,,2022-03-18
998,https://www.huffpost.com/entry/japan-earthquak...,"Strong Japan Earthquake Kills 4, Injures 107",WORLD NEWS,The 7.4-magnitude temblor knocked out power an...,"Mari Yamaguchi, AP",2022-03-17
999,https://www.huffpost.com/entry/fiery-texas-cra...,"9 Dead, 2 Injured In Fiery Crash Involving Uni...",U.S. NEWS,Two Canadian students were also hospitalized i...,"Cedar Attanasio, Jill Bleed and Anita Snow, AP",2022-03-17

In [3]:
dataset = dataset.rename(columns={'headline': 'English'})
dataset= dataset.rename(columns={'short_description': 'French'})
dataset

,link,English,category,French,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
995,https://www.huffpost.com/entry/china-weighs-ex...,China Weighs Exit From 'Zero COVID' And The Ri...,WORLD NEWS,The change does not appear imminent as the gov...,"Dake Kang and Huizhong Wu, AP",2022-03-18
996,https://www.huffpost.com/entry/russian-missile...,Russian Missiles Hit Near Lviv Airport As Stri...,WORLD NEWS,World leaders have been calling for an investi...,"Cara Anna, AP",2022-03-18
997,https://www.huffpost.com/entry/assad-uae_n_623...,"Syria's Assad Visits UAE, 1st Trip To Arab Cou...",WORLD NEWS,Assad's office said he met with Sheikh Mohamed...,,2022-03-18
998,https://www.huffpost.com/entry/japan-earthquak...,"Strong Japan Earthquake Kills 4, Injures 107",WORLD NEWS,The 7.4-magnitude temblor knocked out power an...,"Mari Yamaguchi, AP",2022-03-17
999,https://www.huffpost.com/entry/fiery-texas-cra...,"9 Dead, 2 Injured In Fiery Crash Involving Uni...",U.S. NEWS,Two Canadian students were also hospitalized i...,"Cedar Attanasio, Jill Bleed and Anita Snow, AP",2022-03-17

In [4]:
import re
corpus = []
for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['English'][i])
    review = review.lower()
    review = review.split()

    review = ' '.join(review)
    corpus.append(review)

In [5]:
corpus

['over 4 million americans roll up sleeves for omicron targeted covid boosters',
 'american airlines flyer charged banned for life after punching flight attendant on video',
 '23 of the funniest tweets about cats and dogs this week sept 17 23',
 'the funniest tweets from parents this week sept 17 23',
 'woman who called cops on black bird watcher loses lawsuit against ex employer',
 'cleaner was dead in belk bathroom for 4 days before body found police',
 'reporter gets adorable surprise from her boyfriend while live on tv',
 'puerto ricans desperate for water after hurricane fiona s rampage',
 'how a new documentary captures the complexity of being a child of immigrants',
 'biden at un to call russian war an affront to body s charter',
 'world cup captains want to wear rainbow armbands in qatar',
 'man sets himself on fire in apparent protest of funeral for japan s abe',
 'fiona threatens to become category 4 storm headed to bermuda',
 'twitch bans gambling sites after streamer scams folks out of 200 000',
 'virginia thomas agrees to interview with jan 6 panel',
 'russian cosmonaut valery polyakov who broke record with 437 day stay in space dies at 80',
 'reboot is a clever and not too navel gazey look inside tv reboots',
 'maury wills base stealing shortstop for dodgers dies at 89',
 '4 russian controlled ukrainian regions schedule votes this week to join russia',
 'fiona barrels toward turks and caicos islands as category 3 hurricane',
 'golden globes returning to nbc in january after year off air',
 'biden says u s forces would defend taiwan if china invaded',
 'hurricane fiona bears down on dominican republic after pounding puerto rico',
 'one dead after plane crashes at reno air race',
 'beautiful and sad at the same time ukrainian cultural festival takes on a deeper meaning this year',
 'family of american held in afghanistan says he was freed by taliban in prisoner swap',
 'las vegas aces win first wnba title chelsea gray named mvp',
 'world leaders pay respects to queen elizabeth ii',
 'james cameron says he clashed with studio before avatar release',
 'french spider man celebrates 60th birthday with a massive skyscraper climb',
 'biden says queen s death left giant hole for royal family',
 'watchdog report finds some census takers who fudged 2020 data didn t get fired',
 'first public global database of fossil fuels launches',
 'man charged with exposing himself to mourners waiting to view queen elizabeth',
 'alaska prepares for historic level storm barreling towards coast',
 'puerto rico braces for landslides and severe flooding as tropical storm fiona approaches',
 'who raises alarm on disease in flood hit areas of pakistan',
 'privatization isn t the answer to jackson s water crisis',
 'german customs officials follow trail of slime and find bags of giant snails',
 'amazon greenlights blade runner 2099 limited series produced by ridley scott',
 'bill to help afghans who escaped taliban faces long odds in the senate',
 'alabama sidesteps compensation for survivor of 63 kkk blast',
 'racism seen as root of water crisis in mississippi capital',
 'the phantom of the opera to close on broadway next year',
 'mark meadows complies with justice dept subpoena report',
 'meet alex aster the tiktoker changing the publishing industry for the better',
 'chick fil a worker saves woman with baby from being carjacked',
 'viola davis feared a heart attack during the woman king training',
 'kim kardashian s next boyfriend could be a biochemist',
 'podcasters offer 100k reward for information on 2pac s killers',
 'cardi b donates 100 000 to her old middle school in the bronx',
 'bill richardson visits moscow as brittney griner paul whelan remain jailed',
 'emmy awards viewership dips to a record low as its audience continues to drop',
 'possible nationwide rail strike is already impacting travelers businesses',
 'democrats nominate seth magaziner in key rhode island house race',
 'tiktok search results riddled with misinformation report',
 'u s inflation falls for 2nd straight month on lower gas costs',
 'jean luc godard pioneering french filmmaker dies',
 'thousands of minnesota nurses launch 3 day strike over pay',
 'joe biden urges national unity in speech on renewed cancer moonshot',
 'sen tim scott downplays electability concerns over struggling senate gop candidates',
 'boston marathon to make race more inclusive for nonbinary runners',
 'anthony varvaro mlb pitcher turned transit cop dies in crash on way to 9 11 ceremony',
 'electability is on the ballot in key rhode island house primary',
 'in a nod to jfk joe biden pushing moonshot to fight cancer',
 'how ani liu is brilliantly disguising her art as science',
 'sidney tackles the not so comfortable conversations about a black cinema icon',
 'carlos alcaraz wins u s open for 1st slam title top ranking',
 'weather helping but threat from western fires persists',
 'biden honors 9 11 victims vows commitment to thwart terror',
 '9 11 attacks still reverberate as u s marks 21st anniversary',
 'last reactor at ukraine s zaporizhzhia nuclear plant stopped',
 'payment processor visa to start categorizing sales at gun stores',
 'us trump team propose names for arbiter in mar a lago probe',
 'james cameron presents new scenes from avatar the way of water at d23 expo',
 'russia says it s pulling back forces from ukraine s kharkiv region',
 'severe winds batter southern california as heat wave breaks',
 'ukraine claws back some territory nuclear plant in peril',
 'watch harry styles pay tribute to queen elizabeth ii at nyc concert',
 'ex employee testifies he now doubts r kelly abuse denials',
 'our hearts are broken historic front pages mark the queen s death',
 'jojo siwa to receive prestigious glsen honor for her lgbtq advocacy work',
 'un chief asks world for massive help in flood hit pakistan',
 'politician s dna connected to las vegas journalist s murder police say',
 'michelle obama celebrated for wearing braids to her white house portrait unveiling',
 'norman reedus opens up about walking dead injury i thought i was going to die',
 'michigan supreme court revives abortion rights amendment for november s ballot',
 'portland residents with disabilities sue over city s blocked sidewalks',
 'at least 32 dead in fire at karaoke parlor in south vietnam',
 'baseball players union joins afl cio in show of solidarity with other workers',
 'muslims only make up 1 of characters on tv study finds',
 'the unemployment insurance system is not ready for the next recession',
 'power outage at austin airport leads to flight delays traffic jams',
 'shelling goes on near ukraine nuclear plant despite risks',
 'cyberattack prompts los angeles school district to shut down its computer systems',
 'fast moving fairview fire kills at least 2 in california',
 'kody clemens strikes out mvp shohei ohtani trails dad roger by 4 671 ks',
 'mississippi governor says water pressure is now solid in jackson',
 'meta parent company of instagram fined 400 million by irish regulators',
 'school starts today for survivors of deadly mass shooting in uvalde',
 'u s russia to buy rockets artillery shells from north korea',
 'harry styles say he feels like he has no idea what i m doing when acting',
 'michigan secretary of state worried about violence and disruption going into midterms',
 'citing imminent danger cloudflare drops hate site kiwi farms',
 'bear spotted chilling in california swimming pool',
 'uvalde fourth graders waited an hour with wounded teacher',
 'trump endorsed wisconsin gubernatorial candidate tells voters to take up pitchforks',
 'memphis police arrest made in jogger s disappearance',
 'fema director says it s too early to tell when jackson will have clean water again',
 'pakistan s largest natural lake is rising to dangerous levels due to monsoon',
 'uvalde children grapple with trauma after school massacre',
 'emergency declared as flash flooding hits northwest georgia',
 'the osbournes will return in british revival on bbc same laughter love and tears',
 'plane that circled mississippi threatening to crash has landed',
 'fuel leak ruins nasa s 2nd shot at launching new moon rocket',
 '9 migrants are found dead in rio grande border patrol',
 'owner of new england frozen yogurt shops accused of hiding camera in store bathroom',
 'former white house counsel pat cipollone to testify before grand jury reports',
 'tropical storm danielle strengthens into hurricane no current threat to land',
 'putin plans to snub gorbachev s funeral',
 'nasa aims for saturday launch of new moon rocket after fixing fuel leaks',
 'u s hiring slowed in august as employers add 315 000 jobs',
 'pregnant woman who claimed unborn baby was hov lane passenger receives another ticket',
 'should you freeze dry your breast milk',
 'missing louisiana nun found alive and safe months after armed home raid',
 'a ku klux klan plaque is mounted at west point s science center commission finds',
 'toxic algae causes thousands of dead fish to wash ashore in california',
 'lisa loeb paved her own way in the 90s a rare feat for independent artists of the time',
 'rep jim jordan s judiciary twitter account finds threat in pic of docs at trump home',
 'mikhail gorbachev s 1998 pizza hut ad resurfaces after his death',
 'republicans ignore trump s hoarding of classified documents',
 'fox friends host questions why trump kept classified documents at mar a lago',
 '3 more r kelly accusers testify about his abuse in chicago trial',
 'stocks dive for truth social spac amid merger delay',
 '6 signs you re grinding your teeth at night and what to do about it',
 'safety is always first nasa reschedules artemis moon mission to saturday',
 'secret service official and ex trump aide tony ornato retires amid jan 6 probe',
 'the vow part two trailer dives deeper into downfall of twisted nxivm cult',
 'this breastfeeding condition makes moms feel dread disgust and despair',
 'yung gravy brings addison rae s mom as his vmas date calls her a certain 4 letter word',
 'house members are using a controversial tool to keep campaigning has it gone too far',
 'lindsey graham warns of riots in streets if trump is charged over classified docs',
 'amber heard s sister reacts to disgusting johnny depp cameo at vmas',
 'johnny depp makes surprise appearance as moon person at mtv vmas',
 'and the award for most enthusiastic vmas guest goes to taylor swift',
 'pakistan flooding deaths pass 1 000 in climate catastrophe',
 '2022 mtv vmas red carpet all the wildest looks you need to see',
 'a nebraska man conducted an active shooter drill employees had no idea',
 'kash patel says his life s in danger because he s in fbi affidavit',
 'fbi probing russian speaking fake heiress who infiltrated mar a lago report',
 'arcade fire singer win butler accused of sexual misconduct by several people report',
 'don jr posts dick pic of dad after affidavit release redact this',
 'trump attorneys file do over motion regarding mar a lago search',
 '6 missing college students in mexico were held in warehouse killed by army',
 'a fisherman thought he caught a rock he snagged a prehistoric treasure instead',
 'jared kushner blasts nasty troll chrissy teigen for attacks on ivanka',
 'kimmel host nikki glaser absolutely goes there in scorching nsfw monologue',
 'mar a lago search affidavit trump was insecurely storing most sensitive intel at club',
 'donald trump s truth social reportedly faces major money trademark woes',
 'finish him fighting kangaroo pulls wild move right out of a video game',
 '6 months into war russian goods still flowing to u s',
 'judge temporarily blocks north dakota trigger law banning abortion',
 'rei workers at berkeley store vote to unionize in another win for labor',
 'gov brian kemp fights subpoena in georgia election probe',
 'japan s national police chief to resign over shinzo abe assassination',
 'uvalde victims families survivors plan multi billion dollar lawsuit',
 'dan goldman narrowly leading in new york democratic primary declares victory',
 'markwayne mullin wins oklahoma republican primary to succeed gop sen jim inhofe',
 'charlie crist wins chance to take on florida gov ron desantis and his 132 million',
 'irs launches safety review amid threats to workers linked to conspiracy theories',
 'student loan borrowers await biden plan on debt forgiveness',
 'house of the dragon is already ratings king after most watched hbo premiere ever',
 'former louisville cop pleads guilty in breonna taylor case',
 'jerry allison buddy holly s drummer dead at 82',
 'andrew garfield confirms method acting is possible without being an asshole',
 'rusty bowers rips fascism of gop and trump s strong arm tactics to trash vote',
 'after delay biden readies student loan help payment pause',
 'this is the bittersweet part of democrats sweet legislative victory',
 'uk broadcaster to air satirical musical on prince andrew',
 'teachers in ohio s largest school district go on strike',
 'ukraine 9 000 of its troops killed since russia began war',
 'gas prices are falling but global events could cause increase energy secretary warns',
 'police file terrorism charges against pakistan s ex premier imran khan',
 'minneapolis teacher contract race language ignites firestorm',
 'hawaii seeking end to conflict over astronomy on sacred mountain',
 'metal detecting stranger retrieves woman s ring lost in sea',
 'leon vitali stanley kubrick s right hand man dies at 74',
 'dragon ball super bests beast at box office with 20 1m',
 'defense in parkland school shooter s trial set to present its case',
 'judge won t block georgia ban on bringing food water to voters in line',
 'trans woman can t be considered parent of her own child rules tokyo court',
 'dorli rainey symbol of occupy movement dies at 95',
 'mike pence says he did not take classified documents when he left office',
 'wendy s pulls lettuce from sandwiches after dozens fall sick from e coli',
 'shocking drone video shows alligator attacking florida man',
 'how to tell if your chest pain is a heart problem',
 'mitch mcconnell gives downbeat forecast on gop winning senate',
 'vanessa bryant says kobe bryant crash photos turned grief to horror',
 'rapper young thug again denied bond in racketeering and gang case',
 'media to ask judge to release trump search warrant affidavit',
 'state dept studying 34 year sentence of saudi woman over twitter use',
 'lgbtq pride events will have priority access to monkeypox vaccines health officials say',
 'trump org cfo to plead guilty testify against company',
 'deshaun watson settles with nfl for 11 game suspension',
 'mike and the flawed allure of authorized biopics',
 'talks on possible watson settlement progress',
 'cdc director to overhaul agency with covid shortcomings in mind',
 'general motors recalls over 484 000 vehicles over improperly formed seat belts',
 'planned parenthood to spend record 50 million for midterms',
 'former california congressman charged after multiple fraud schemes feds say',
 'syria denies it is holding american journalist austin tice',
 'nba won t host election day games in effort to increase voter turnout',
 'dog catches monkeypox in france in first suspected human to pet transmission',
 'the denver broncos historic purchase could increase number of minority owned nfl teams',
 'new law makes period products free for all in scotland',
 'tiger to meet with top players against liv golf',
 'afghanistan marks one year anniversary since taliban takeover',
 'lindsey graham must testify in georgia election probe judge says',
 'another world soap star robyn griggs dies at 49',
 '3 injured in shooting at six flags great america park near chicago',
 'iran denies involvement but justifies salman rushdie attack',
 'lawyers appeal brittney griner s russian prison sentence',
 'jury selection in r kelly federal trial to begin in chicago',
 'palestinian gunman wounds 8 in late night jerusalem shooting',
 'bullet train repeats no 1 top gun flies back up ranks',
 'officials fire at coptic church in cairo kills 41',
 'don t look up a possible meteor causes loud boom sound in utah',
 'salman rushdie on the road to recovery agent says',
 'catastrophic failure at research center kills about 21 000 fish',
 'parents arrested after attempting to grab their children during school lockdown',
 'sinema took wall street money while killing tax on investors',
 'video shows nfl player hopping into stands to stop fighting fans',
 'suspect in rushdie stabbing pleads not guilty as author remains hospitalized',
 'shocking fish die off sends poland scrambling to determine source',
 'cleveland browns qb deshaun watson apologizes to all the women i have impacted',
 'over 2 billion announced for roads bridges bike lanes across u s',
 'polio detected in nyc s sewage suggesting virus circulating',
 'democrats inflation reduction act expected to do little to reduce inflation',
 'cdc drops some quarantine screening recommendations for covid 19',
 'feathers fly as wild turkey dodges cops in slapstick apartment chase',
 'steve martin says only murders in the building could be his final role',
 'officials nh missing girl case shifts to homicide probe',
 'u s unemployment claims rise to highest level since november',
 'gas prices dip just below 4 for the first time in 5 months',
 'as joe biden wins mount 2024 doubts ease for top house dems',
 'fx s justified set faces violent interruption for second time in 3 weeks',
 'ex twitter staffer convicted for sharing private information on dissidents with saudis',
 'stranded whale euthanized after removal from french river',
 'sesame place to train workers on diversity after lawsuit',
 'kobe bryant crash photos lawsuit to be heard by la jury',
 'why the justice department can t say more about the mar a lago raid',
 'lawyer rudy giuliani won t testify tuesday in georgia election probe',
 'idris elba reveals how he hustled his way onto jay z s american gangster album',
 'judge 3 players who joined saudi backed golf tour can t compete in pga postseason',
 'broncos make history after being sold for record 4 65 billion',
 '3 dead in shooting at florida narcotics anonymous meeting',
 'trump said wounded veterans in military parades didn t look good for him book',
 'lindsey graham scolded for senate outburst at maggie hassan',
 'albuquerque police share photo of car eyed in slayings of muslim men',
 'come on bernie why democrats left child tax credit out of the inflation reduction act',
 'how to hide even the worst tan lines according to makeup pros',
 '57 votes in the senate enough for private equity not enough for diabetics',
 'brad pitt s bullet train pulls into station with 30 1m',
 'the flash movie still set for release despite ezra miller s controversies',
 'biden expresses solidarity with muslim community after albuquerque killings',
 'l a man among 3 killed in lightning strike near white house',
 'over 120 injured several missing in massive cuban oil facility fire',
 'eastern kentucky braces for more storms while recovering from extreme flooding',
 'woody harrelson reacts to viral photo of doppelg nger baby with sweet poem',
 'albuquerque police tell muslim community to be vigilant amid series of murders',
 'canadian man uses giant billboard to get rid of leftover dairy product in fridge',
 'new york couple turns in 5 foot gator zachary they d been keeping in home',
 'this is the most underappreciated part of the democratic prescription drug bill',
 'gop senators refuse to rule out supporting donald trump again even if he s indicted',
 'cpac has a special exhibit a sobbing jan 6 rioter in jail',
 '5 dead 8 injured in fiery los angeles crash after speeding car runs red light',
 'trevor noah busts putin for another s tty thing he s doing to screw with u s',
 'french scientist trolls twitter by claiming chorizo slice is actually a distant star',
 'fertility treatment puts many families in debt here s how to manage it',

In [6]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))   # Simple Preprcoess make it lowe r case
words

[['over',
  'million',
  'americans',
  'roll',
  'up',
  'sleeves',
  'for',
  'omicron',
  'targeted',
  'covid',
  'boosters'],
 ['american',
  'airlines',
  'flyer',
  'charged',
  'banned',
  'for',
  'life',
  'after',
  'punching',
  'flight',
  'attendant',
  'on',
  'video'],
 ['of',
  'the',
  'funniest',
  'tweets',
  'about',
  'cats',
  'and',
  'dogs',
  'this',
  'week',
  'sept'],
 ['the', 'funniest', 'tweets', 'from', 'parents', 'this', 'week', 'sept'],
 ['woman',
  'who',
  'called',
  'cops',
  'on',
  'black',
  'bird',
  'watcher',
  'loses',
  'lawsuit',
  'against',
  'ex',
  'employer'],
 ['cleaner',
  'was',
  'dead',
  'in',
  'belk',
  'bathroom',
  'for',
  'days',
  'before',
  'body',
  'found',
  'police'],
 ['reporter',
  'gets',
  'adorable',
  'surprise',
  'from',
  'her',
  'boyfriend',
  'while',
  'live',
  'on',
  'tv'],
 ['puerto',
  'ricans',
  'desperate',
  'for',
  'water',
  'after',
  'hurricane',
  'fiona',
  'rampage'],
 ['how',
  'new',
  'documentary',
  'captures',
  'the',
  'complexity',
  'of',
  'being',
  'child',
  'of',
  'immigrants'],
 ['biden',
  'at',
  'un',
  'to',
  'call',
  'russian',
  'war',
  'an',
  'affront',
  'to',
  'body',
  'charter'],
 ['world',
  'cup',
  'captains',
  'want',
  'to',
  'wear',
  'rainbow',
  'armbands',
  'in',
  'qatar'],
 ['man',
  'sets',
  'himself',
  'on',
  'fire',
  'in',
  'apparent',
  'protest',
  'of',
  'funeral',
  'for',
  'japan',
  'abe'],
 ['fiona',
  'threatens',
  'to',
  'become',
  'category',
  'storm',
  'headed',
  'to',
  'bermuda'],
 ['twitch',
  'bans',
  'gambling',
  'sites',
  'after',
  'streamer',
  'scams',
  'folks',
  'out',
  'of'],
 ['virginia', 'thomas', 'agrees', 'to', 'interview', 'with', 'jan', 'panel'],
 ['russian',
  'cosmonaut',
  'valery',
  'polyakov',
  'who',
  'broke',
  'record',
  'with',
  'day',
  'stay',
  'in',
  'space',
  'dies',
  'at'],
 ['reboot',
  'is',
  'clever',
  'and',
  'not',
  'too',
  'navel',
  'gazey',
  'look',
  'inside',
  'tv',
  'reboots'],
 ['maury',
  'wills',
  'base',
  'stealing',
  'shortstop',
  'for',
  'dodgers',
  'dies',
  'at'],
 ['russian',
  'controlled',
  'ukrainian',
  'regions',
  'schedule',
  'votes',
  'this',
  'week',
  'to',
  'join',
  'russia'],
 ['fiona',
  'barrels',
  'toward',
  'turks',
  'and',
  'caicos',
  'islands',
  'as',
  'category',
  'hurricane'],
 ['golden',
  'globes',
  'returning',
  'to',
  'nbc',
  'in',
  'january',
  'after',
  'year',
  'off',
  'air'],
 ['biden',
  'says',
  'forces',
  'would',
  'defend',
  'taiwan',
  'if',
  'china',
  'invaded'],
 ['hurricane',
  'fiona',
  'bears',
  'down',
  'on',
  'dominican',
  'republic',
  'after',
  'pounding',
  'puerto',
  'rico'],
 ['one', 'dead', 'after', 'plane', 'crashes', 'at', 'reno', 'air', 'race'],
 ['beautiful',
  'and',
  'sad',
  'at',
  'the',
  'same',
  'time',
  'ukrainian',
  'cultural',
  'festival',
  'takes',
  'on',
  'deeper',
  'meaning',
  'this',
  'year'],
 ['family',
  'of',
  'american',
  'held',
  'in',
  'afghanistan',
  'says',
  'he',
  'was',
  'freed',
  'by',
  'taliban',
  'in',
  'prisoner',
  'swap'],
 ['las',
  'vegas',
  'aces',
  'win',
  'first',
  'wnba',
  'title',
  'chelsea',
  'gray',
  'named',
  'mvp'],
 ['world', 'leaders', 'pay', 'respects', 'to', 'queen', 'elizabeth', 'ii'],
 ['james',
  'cameron',
  'says',
  'he',
  'clashed',
  'with',
  'studio',
  'before',
  'avatar',
  'release'],
 ['french',
  'spider',
  'man',
  'celebrates',
  'th',
  'birthday',
  'with',
  'massive',
  'skyscraper',
  'climb'],
 ['biden',
  'says',
  'queen',
  'death',
  'left',
  'giant',
  'hole',
  'for',
  'royal',
  'family'],
 ['watchdog',
  'report',
  'finds',
  'some',
  'census',
  'takers',
  'who',
  'fudged',
  'data',
  'didn',
  'get',
  'fired'],
 ['first',
  'public',
  'global',
  'database',
  'of',
  'fossil',
  'fuels',
  'launches'],
 ['man',
  'charged',
  'with',
  'exposing',
  'himself',
  'to',
  'mourners',
  'waiting',
  'to',
  'view',
  'queen',
  'elizabeth'],
 ['alaska',
  'prepares',
  'for',
  'historic',
  'level',
  'storm',
  'barreling',
  'towards',
  'coast'],
 ['puerto',
  'rico',
  'braces',
  'for',
  'landslides',
  'and',
  'severe',
  'flooding',
  'as',
  'tropical',
  'storm',
  'fiona',
  'approaches'],
 ['who',
  'raises',
  'alarm',
  'on',
  'disease',
  'in',
  'flood',
  'hit',
  'areas',
  'of',
  'pakistan'],
 ['privatization', 'isn', 'the', 'answer', 'to', 'jackson', 'water', 'crisis'],
 ['german',
  'customs',
  'officials',
  'follow',
  'trail',
  'of',
  'slime',
  'and',
  'find',
  'bags',
  'of',
  'giant',
  'snails'],
 ['amazon',
  'greenlights',
  'blade',
  'runner',
  'limited',
  'series',
  'produced',
  'by',
  'ridley',
  'scott'],
 ['bill',
  'to',
  'help',
  'afghans',
  'who',
  'escaped',
  'taliban',
  'faces',
  'long',
  'odds',
  'in',
  'the',
  'senate'],
 ['alabama',
  'sidesteps',
  'compensation',
  'for',
  'survivor',
  'of',
  'kkk',
  'blast'],
 ['racism',
  'seen',
  'as',
  'root',
  'of',
  'water',
  'crisis',
  'in',
  'mississippi',
  'capital'],
 ['the',
  'phantom',
  'of',
  'the',
  'opera',
  'to',
  'close',
  'on',
  'broadway',
  'next',
  'year'],
 ['mark',
  'meadows',
  'complies',
  'with',
  'justice',
  'dept',
  'subpoena',
  'report'],
 ['meet',
  'alex',
  'aster',
  'the',
  'tiktoker',
  'changing',
  'the',
  'publishing',
  'industry',
  'for',
  'the',
  'better'],
 ['chick',
  'fil',
  'worker',
  'saves',
  'woman',
  'with',
  'baby',
  'from',
  'being',
  'carjacked'],
 ['viola',
  'davis',
  'feared',
  'heart',
  'attack',
  'during',
  'the',
  'woman',
  'king',
  'training'],
 ['kim', 'kardashian', 'next', 'boyfriend', 'could', 'be', 'biochemist'],
 ['podcasters',
  'offer',
  'reward',
  'for',
  'information',
  'on',
  'pac',
  'killers'],
 ['cardi',
  'donates',
  'to',
  'her',
  'old',
  'middle',
  'school',
  'in',
  'the',
  'bronx'],
 ['bill',
  'richardson',
  'visits',
  'moscow',
  'as',
  'brittney',
  'griner',
  'paul',
  'whelan',
  'remain',
  'jailed'],
 ['emmy',
  'awards',
  'viewership',
  'dips',
  'to',
  'record',
  'low',
  'as',
  'its',
  'audience',
  'continues',
  'to',
  'drop'],
 ['possible',
  'nationwide',
  'rail',
  'strike',
  'is',
  'already',
  'impacting',
  'travelers',
  'businesses'],
 ['democrats',
  'nominate',
  'seth',
  'magaziner',
  'in',
  'key',
  'rhode',
  'island',
  'house',
  'race'],
 ['tiktok',
  'search',
  'results',
  'riddled',
  'with',
  'misinformation',
  'report'],
 ['inflation',
  'falls',
  'for',
  'nd',
  'straight',
  'month',
  'on',
  'lower',
  'gas',
  'costs'],
 ['jean', 'luc', 'godard', 'pioneering', 'french', 'filmmaker', 'dies'],
 ['thousands',
  'of',
  'minnesota',
  'nurses',
  'launch',
  'day',
  'strike',
  'over',
  'pay'],
 ['joe',
  'biden',
  'urges',
  'national',
  'unity',
  'in',
  'speech',
  'on',
  'renewed',
  'cancer',
  'moonshot'],
 ['sen',
  'tim',
  'scott',
  'downplays',
  'electability',
  'concerns',
  'over',
  'struggling',
  'senate',
  'gop',
  'candidates'],
 ['boston',
  'marathon',
  'to',
  'make',
  'race',
  'more',
  'inclusive',
  'for',
  'nonbinary',
  'runners'],
 ['anthony',
  'varvaro',
  'mlb',
  'pitcher',
  'turned',
  'transit',
  'cop',
  'dies',
  'in',
  'crash',
  'on',
  'way',
  'to',
  'ceremony'],
 ['electability',
  'is',
  'on',
  'the',
  'ballot',
  'in',
  'key',
  'rhode',
  'island',
  'house',
  'primary'],
 ['in',
  'nod',
  'to',
  'jfk',
  'joe',
  'biden',
  'pushing',
  'moonshot',
  'to',
  'fight',
  'cancer'],
 ['how',
  'ani',
  'liu',
  'is',
  'brilliantly',
  'disguising',
  'her',
  'art',
  'as',
  'science'],
 ['sidney',
  'tackles',
  'the',
  'not',
  'so',
  'comfortable',
  'conversations',
  'about',
  'black',
  'cinema',
  'icon'],
 ['carlos',
  'alcaraz',
  'wins',
  'open',
  'for',
  'st',
  'slam',
  'title',
  'top',
  'ranking'],
 ['weather',
  'helping',
  'but',
  'threat',
  'from',
  'western',
  'fires',
  'persists'],
 ['biden',
  'honors',
  'victims',
  'vows',
  'commitment',
  'to',
  'thwart',
  'terror'],
 ['attacks', 'still', 'reverberate', 'as', 'marks', 'st', 'anniversary'],
 ['last',
  'reactor',
  'at',
  'ukraine',
  'zaporizhzhia',
  'nuclear',
  'plant',
  'stopped'],
 ['payment',
  'processor',
  'visa',
  'to',
  'start',
  'categorizing',
  'sales',
  'at',
  'gun',
  'stores'],
 ['us',
  'trump',
  'team',
  'propose',
  'names',
  'for',
  'arbiter',
  'in',
  'mar',
  'lago',
  'probe'],
 ['james',
  'cameron',
  'presents',
  'new',
  'scenes',
  'from',
  'avatar',
  'the',
  'way',
  'of',
  'water',
  'at',
  'expo'],
 ['russia',
  'says',
  'it',
  'pulling',
  'back',
  'forces',
  'from',
  'ukraine',
  'kharkiv',
  'region'],
 ['severe',
  'winds',
  'batter',
  'southern',
  'california',
  'as',
  'heat',
  'wave',
  'breaks'],
 ['ukraine',
  'claws',
  'back',
  'some',
  'territory',
  'nuclear',
  'plant',
  'in',
  'peril'],
 ['watch',
  'harry',
  'styles',
  'pay',
  'tribute',
  'to',
  'queen',
  'elizabeth',
  'ii',
  'at',
  'nyc',
  'concert'],
 ['ex',
  'employee',
  'testifies',
  'he',
  'now',
  'doubts',
  'kelly',
  'abuse',
  'denials'],
 ['our',
  'hearts',
  'are',
  'broken',
  'historic',
  'front',
  'pages',
  'mark',
  'the',
  'queen',
  'death'],
 ['jojo',
  'siwa',
  'to',
  'receive',
  'prestigious',
  'glsen',
  'honor',
  'for',
  'her',
  'lgbtq',
  'advocacy',
  'work'],
 ['un',
  'chief',
  'asks',
  'world',
  'for',
  'massive',
  'help',
  'in',
  'flood',
  'hit',
  'pakistan'],
 ['politician',
  'dna',
  'connected',
  'to',
  'las',
  'vegas',
  'journalist',
  'murder',
  'police',
  'say'],
 ['michelle',
  'obama',
  'celebrated',
  'for',
  'wearing',
  'braids',
  'to',
  'her',
  'white',
  'house',
  'portrait',
  'unveiling'],
 ['norman',
  'reedus',
  'opens',
  'up',
  'about',
  'walking',
  'dead',
  'injury',
  'thought',
  'was',
  'going',
  'to',
  'die'],
 ['michigan',
  'supreme',
  'court',
  'revives',
  'abortion',
  'rights',
  'amendment',
  'for',
  'november',
  'ballot'],
 ['portland',
  'residents',
  'with',
  'disabilities',
  'sue',
  'over',
  'city',
  'blocked',
  'sidewalks'],
 ['at',
  'least',
  'dead',
  'in',
  'fire',
  'at',
  'karaoke',
  'parlor',
  'in',
  'south',
  'vietnam'],
 ['baseball',
  'players',
  'union',
  'joins',
  'afl',
  'cio',
  'in',
  'show',
  'of',
  'solidarity',
  'with',
  'other',
  'workers'],
 ['muslims',
  'only',
  'make',
  'up',
  'of',
  'characters',
  'on',
  'tv',
  'study',
  'finds'],
 ['the',
  'unemployment',
  'insurance',
  'system',
  'is',
  'not',
  'ready',
  'for',
  'the',
  'next',
  'recession'],
 ['power',
  'outage',
  'at',
  'austin',
  'airport',
  'leads',
  'to',
  'flight',
  'delays',
  'traffic',
  'jams'],
 ['shelling',
  'goes',
  'on',
  'near',
  'ukraine',
  'nuclear',
  'plant',
  'despite',
  'risks'],
 ['cyberattack',
  'prompts',
  'los',
  'angeles',
  'school',
  'district',
  'to',
  'shut',
  'down',
  'its',
  'computer',
  'systems'],
 ['fast',
  'moving',
  'fairview',
  'fire',
  'kills',
  'at',
  'least',
  'in',
  'california'],
 ['kody',
  'clemens',
  'strikes',
  'out',
  'mvp',
  'shohei',
  'ohtani',
  'trails',
  'dad',
  'roger',
  'by',
  'ks'],
 ['mississippi',
  'governor',
  'says',
  'water',
  'pressure',
  'is',
  'now',
  'solid',
  'in',
  'jackson'],
 ['meta',
  'parent',
  'company',
  'of',
  'instagram',
  'fined',
  'million',
  'by',
  'irish',
  'regulators'],
 ['school',
  'starts',
  'today',
  'for',
  'survivors',
  'of',
  'deadly',
  'mass',
  'shooting',
  'in',
  'uvalde'],
 ['russia',
  'to',
  'buy',
  'rockets',
  'artillery',
  'shells',
  'from',
  'north',
  'korea'],
 ['harry',
  'styles',
  'say',
  'he',
  'feels',
  'like',
  'he',
  'has',
  'no',
  'idea',
  'what',
  'doing',
  'when',
  'acting'],
 ['michigan',
  'secretary',
  'of',
  'state',
  'worried',
  'about',
  'violence',
  'and',
  'disruption',
  'going',
  'into',
  'midterms'],
 ['citing',
  'imminent',
  'danger',
  'cloudflare',
  'drops',
  'hate',
  'site',
  'kiwi',
  'farms'],
 ['bear', 'spotted', 'chilling', 'in', 'california', 'swimming', 'pool'],
 ['uvalde',
  'fourth',
  'graders',
  'waited',
  'an',
  'hour',
  'with',
  'wounded',
  'teacher'],
 ['trump',
  'endorsed',
  'wisconsin',
  'gubernatorial',
  'candidate',
  'tells',
  'voters',
  'to',
  'take',
  'up',
  'pitchforks'],
 ['memphis', 'police', 'arrest', 'made', 'in', 'jogger', 'disappearance'],
 ['fema',
  'director',
  'says',
  'it',
  'too',
  'early',
  'to',
  'tell',
  'when',
  'jackson',
  'will',
  'have',
  'clean',
  'water',
  'again'],
 ['pakistan',
  'largest',
  'natural',
  'lake',
  'is',
  'rising',
  'to',
  'dangerous',
  'levels',
  'due',
  'to',
  'monsoon'],
 ['uvalde',
  'children',
  'grapple',
  'with',
  'trauma',
  'after',
  'school',
  'massacre'],
 ['emergency',
  'declared',
  'as',
  'flash',
  'flooding',
  'hits',
  'northwest',
  'georgia'],
 ['the',
  'osbournes',
  'will',
  'return',
  'in',
  'british',
  'revival',
  'on',
  'bbc',
  'same',
  'laughter',
  'love',
  'and',
  'tears'],
 ['plane',
  'that',
  'circled',
  'mississippi',
  'threatening',
  'to',
  'crash',
  'has',
  'landed'],
 ['fuel',
  'leak',
  'ruins',
  'nasa',
  'nd',
  'shot',
  'at',
  'launching',
  'new',
  'moon',
  'rocket'],
 ['migrants',
  'are',
  'found',
  'dead',
  'in',
  'rio',
  'grande',
  'border',
  'patrol'],
 ['owner',
  'of',
  'new',
  'england',
  'frozen',
  'yogurt',
  'shops',
  'accused',
  'of',
  'hiding',
  'camera',
  'in',
  'store',
  'bathroom'],
 ['former',
  'white',
  'house',
  'counsel',
  'pat',
  'cipollone',
  'to',
  'testify',
  'before',
  'grand',
  'jury',
  'reports'],
 ['tropical',
  'storm',
  'danielle',
  'strengthens',
  'into',
  'hurricane',
  'no',
  'current',
  'threat',
  'to',
  'land'],
 ['putin', 'plans', 'to', 'snub', 'gorbachev', 'funeral'],
 ['nasa',
  'aims',
  'for',
  'saturday',
  'launch',
  'of',
  'new',
  'moon',
  'rocket',
  'after',
  'fixing',
  'fuel',
  'leaks'],
 ['hiring', 'slowed', 'in', 'august', 'as', 'employers', 'add', 'jobs'],
 ['pregnant',
  'woman',
  'who',
  'claimed',
  'unborn',
  'baby',
  'was',
  'hov',
  'lane',
  'passenger',
  'receives',
  'another',
  'ticket'],
 ['should', 'you', 'freeze', 'dry', 'your', 'breast', 'milk'],
 ['missing',
  'louisiana',
  'nun',
  'found',
  'alive',
  'and',
  'safe',
  'months',
  'after',
  'armed',
  'home',
  'raid'],
 ['ku',
  'klux',
  'klan',
  'plaque',
  'is',
  'mounted',
  'at',
  'west',
  'point',
  'science',
  'center',
  'commission',
  'finds'],
 ['toxic',
  'algae',
  'causes',
  'thousands',
  'of',
  'dead',
  'fish',
  'to',
  'wash',
  'ashore',
  'in',
  'california'],
 ['lisa',
  'loeb',
  'paved',
  'her',
  'own',
  'way',
  'in',
  'the',
  'rare',
  'feat',
  'for',
  'independent',
  'artists',
  'of',
  'the',
  'time'],
 ['rep',
  'jim',
  'jordan',
  'judiciary',
  'twitter',
  'account',
  'finds',
  'threat',
  'in',
  'pic',
  'of',
  'docs',
  'at',
  'trump',
  'home'],
 ['mikhail',
  'gorbachev',
  'pizza',
  'hut',
  'ad',
  'resurfaces',
  'after',
  'his',
  'death'],
 ['republicans',
  'ignore',
  'trump',
  'hoarding',
  'of',
  'classified',
  'documents'],
 ['fox',
  'friends',
  'host',
  'questions',
  'why',
  'trump',
  'kept',
  'classified',
  'documents',
  'at',
  'mar',
  'lago'],
 ['more',
  'kelly',
  'accusers',
  'testify',
  'about',
  'his',
  'abuse',
  'in',
  'chicago',
  'trial'],
 ['stocks',
  'dive',
  'for',
  'truth',
  'social',
  'spac',
  'amid',
  'merger',
  'delay'],
 ['signs',
  'you',
  're',
  'grinding',
  'your',
  'teeth',
  'at',
  'night',
  'and',
  'what',
  'to',
  'do',
  'about',
  'it'],
 ['safety',
  'is',
  'always',
  'first',
  'nasa',
  'reschedules',
  'artemis',
  'moon',
  'mission',
  'to',
  'saturday'],
 ['secret',
  'service',
  'official',
  'and',
  'ex',
  'trump',
  'aide',
  'tony',
  'ornato',
  'retires',
  'amid',
  'jan',
  'probe'],
 ['the',
  'vow',
  'part',
  'two',
  'trailer',
  'dives',
  'deeper',
  'into',
  'downfall',
  'of',
  'twisted',
  'nxivm',
  'cult'],
 ['this',
  'breastfeeding',
  'condition',
  'makes',
  'moms',
  'feel',
  'dread',
  'disgust',
  'and',
  'despair'],
 ['yung',
  'gravy',
  'brings',
  'addison',
  'rae',
  'mom',
  'as',
  'his',
  'vmas',
  'date',
  'calls',
  'her',
  'certain',
  'letter',
  'word'],
 ['house',
  'members',
  'are',
  'using',
  'controversial',
  'tool',
  'to',
  'keep',
  'campaigning',
  'has',
  'it',
  'gone',
  'too',
  'far'],
 ['lindsey',
  'graham',
  'warns',
  'of',
  'riots',
  'in',
  'streets',
  'if',
  'trump',
  'is',
  'charged',
  'over',
  'classified',
  'docs'],
 ['amber',
  'heard',
  'sister',
  'reacts',
  'to',
  'disgusting',
  'johnny',
  'depp',
  'cameo',
  'at',
  'vmas'],
 ['johnny',
  'depp',
  'makes',
  'surprise',
  'appearance',
  'as',
  'moon',
  'person',
  'at',
  'mtv',
  'vmas'],
 ['and',
  'the',
  'award',
  'for',
  'most',
  'enthusiastic',
  'vmas',
  'guest',
  'goes',
  'to',
  'taylor',
  'swift'],
 ['pakistan', 'flooding', 'deaths', 'pass', 'in', 'climate', 'catastrophe'],
 ['mtv',
  'vmas',
  'red',
  'carpet',
  'all',
  'the',
  'wildest',
  'looks',
  'you',
  'need',
  'to',
  'see'],
 ['nebraska',
  'man',
  'conducted',
  'an',
  'active',
  'shooter',
  'drill',
  'employees',
  'had',
  'no',
  'idea'],
 ['kash',
  'patel',
  'says',
  'his',
  'life',
  'in',
  'danger',
  'because',
  'he',
  'in',
  'fbi',
  'affidavit'],
 ['fbi',
  'probing',
  'russian',
  'speaking',
  'fake',
  'heiress',
  'who',
  'infiltrated',
  'mar',
  'lago',
  'report'],
 ['arcade',
  'fire',
  'singer',
  'win',
  'butler',
  'accused',
  'of',
  'sexual',
  'misconduct',
  'by',
  'several',
  'people',
  'report'],
 ['don',
  'jr',
  'posts',
  'dick',
  'pic',
  'of',
  'dad',
  'after',
  'affidavit',
  'release',
  'redact',
  'this'],
 ['trump',
  'attorneys',
  'file',
  'do',
  'over',
  'motion',
  'regarding',
  'mar',
  'lago',
  'search'],
 ['missing',
  'college',
  'students',
  'in',
  'mexico',
  'were',
  'held',
  'in',
  'warehouse',
  'killed',
  'by',
  'army'],
 ['fisherman',
  'thought',
  'he',
  'caught',
  'rock',
  'he',
  'snagged',
  'prehistoric',
  'treasure',
  'instead'],
 ['jared',
  'kushner',
  'blasts',
  'nasty',
  'troll',
  'chrissy',
  'teigen',
  'for',
  'attacks',
  'on',
  'ivanka'],
 ['kimmel',
  'host',
  'nikki',
  'glaser',
  'absolutely',
  'goes',
  'there',
  'in',
  'scorching',
  'nsfw',
  'monologue'],
 ['mar',
  'lago',
  'search',
  'affidavit',
  'trump',
  'was',
  'insecurely',
  'storing',
  'most',
  'sensitive',
  'intel',
  'at',
  'club'],
 ['donald',
  'trump',
  'truth',
  'social',
  'reportedly',
  'faces',
  'major',
  'money',
  'trademark',
  'woes'],
 ['finish',
  'him',
  'fighting',
  'kangaroo',
  'pulls',
  'wild',
  'move',
  'right',
  'out',
  'of',
  'video',
  'game'],
 ['months', 'into', 'war', 'russian', 'goods', 'still', 'flowing', 'to'],
 ['judge',
  'temporarily',
  'blocks',
  'north',
  'dakota',
  'trigger',
  'law',
  'banning',
  'abortion'],
 ['rei',
  'workers',
  'at',
  'berkeley',
  'store',
  'vote',
  'to',
  'unionize',
  'in',
  'another',
  'win',
  'for',
  'labor'],
 ['gov',
  'brian',
  'kemp',
  'fights',
  'subpoena',
  'in',
  'georgia',
  'election',
  'probe'],
 ['japan',
  'national',
  'police',
  'chief',
  'to',
  'resign',
  'over',
  'shinzo',
  'abe',
  'assassination'],
 ['uvalde',
  'victims',
  'families',
  'survivors',
  'plan',
  'multi',
  'billion',
  'dollar',
  'lawsuit'],
 ['dan',
  'goldman',
  'narrowly',
  'leading',
  'in',
  'new',
  'york',
  'democratic',
  'primary',
  'declares',
  'victory'],
 ['markwayne',
  'mullin',
  'wins',
  'oklahoma',

In [7]:
all_words = [word for sentence in words for word in sentence]

# Get unique words
unique_words_input = set(all_words)

# Count them
print("Number of unique words:", len(unique_words_input))
print("Unique words:", unique_words_input)

Number of unique words: 3994

In [8]:
max_len_input = max(len(sentence) for sentence in words)
longest_sentence = max(words, key=len)

print("Max number of words:", max_len_input)
print("Sentence with max words:", longest_sentence)

Max number of words: 17
Sentence with max words: ['alex', 'jones', 'sandy', 'hook', 'defamation', 'trial', 'is', 'set', 'to', 'begin', 'here', 'how', 'it', 'got', 'to', 'this', 'point']

## Input Encoding:

In [9]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [10]:
one_hot_input=[one_hot(word, len(unique_words_input)) for word in corpus]
one_hot_input

[[913, 3614, 1523, 2206, 1374, 3765, 428, 2533, 2235, 3737, 2873, 3682],
 [1228, 1553, 1284, 2581, 318, 2533, 1411, 2025, 1990, 92, 3222, 902, 730],
 [3586,
  827,
  3504,
  3593,
  2550,
  2585,
  1666,
  1081,
  343,
  2435,
  233,
  2942,
  1197,
  3586],
 [3504, 3593, 2550, 2931, 205, 2435, 233, 2942, 1197, 3586],
 [3715, 2945, 730, 1454, 902, 149, 598, 470, 3270, 731, 2604, 1817, 3056],
 [11, 2351, 1886, 498, 1135, 1283, 2533, 3614, 1818, 1339, 977, 2239, 1159],
 [2557, 2160, 3225, 3854, 2931, 93, 219, 917, 3358, 902, 364],
 [3989, 483, 96, 2533, 2544, 2025, 2578, 727, 277, 644],
 [788, 2945, 3935, 2515, 3876, 3504, 1513, 827, 686, 2945, 3876, 827, 2360],
 [897, 3906, 1512, 3936, 1776, 1354, 502, 3029, 2140, 3936, 977, 277, 1909],
 [1819, 3497, 1365, 3527, 3936, 3145, 2204, 2788, 498, 3458],
 [3947,
  2379,
  3063,
  902,
  1703,
  498,
  2264,
  2877,
  827,
  3558,
  2533,
  2560,
  277,
  2989],
 [727, 3667, 3936, 829, 1611, 3614, 1435, 540, 3936, 1584],
 [3598, 3910, 1777, 3952, 2025, 195, 58, 680, 2158, 827, 1268, 566],
 [272, 409, 3286, 3936, 3187, 1534, 3942, 1588, 133],
 [1354,
  2254,
  952,
  1500,
  2945,
  3280,
  3426,
  1534,
  1325,
  3984,
  1886,
  498,
  2701,
  2519,
  3906,
  1797],
 [3032, 2952, 2945, 982, 1081, 566, 565, 2560, 3761, 1645, 2099, 364, 145],
 [358, 1371, 1845, 3920, 3879, 2533, 2431, 2519, 3906, 3267],
 [3614, 1354, 1443, 233, 422, 3237, 1251, 2435, 233, 3936, 2519, 3757],
 [727, 65, 3210, 2682, 1081, 3037, 1819, 1536, 1611, 1754, 2578],
 [1758, 1693, 2109, 3936, 1539, 498, 1223, 2025, 3090, 3148, 779],
 [897, 655, 3952, 277, 1835, 3029, 180, 1791, 2540, 2967, 2409],
 [2578, 727, 3618, 3440, 902, 2036, 2872, 2025, 3198, 3989, 1258],
 [3159, 1886, 2025, 3785, 1516, 3906, 3811, 779, 1737],
 [831,
  1081,
  575,
  3906,
  3504,
  128,
  3066,
  233,
  530,
  1977,
  3885,
  902,
  2945,
  2098,
  3844,
  2435,
  3090],
 [734,
  827,
  1228,
  3650,
  498,
  2265,
  655,
  3580,
  2351,
  2087,
  3169,
  3059,
  498,
  2715,
  1528],
 [648, 3745, 2133, 3365, 2015, 1253, 3696, 3188, 2274, 158, 2658],
 [1819, 1797, 3063, 305, 3936, 1021, 1723, 3818],
 [2921, 781, 655, 3580, 683, 1534, 2659, 1339, 1287, 3496],
 [3705, 639, 3947, 2233, 2527, 5, 1534, 2945, 1291, 206, 3554],
 [897, 655, 1021, 277, 3206, 1085, 1842, 3298, 2533, 1434, 734],
 [3093,
  1946,
  1111,
  3537,
  2175,
  3335,
  2945,
  2632,
  2216,
  1758,
  1303,
  699,
  2583,
  3176],
 [2015, 691, 1787, 761, 827, 813, 2402, 2467],
 [3947, 2581, 1534, 745, 3063, 3936, 1750, 1707, 3936, 2063, 1021, 1723],
 [1817, 3457, 2533, 416, 3578, 1435, 1456, 742, 2535],
 [3989, 1258, 2177, 2533, 2457, 1081, 1633, 715, 1536, 2562, 1435, 727, 3852],
 [2945, 1121, 2401, 902, 3710, 498, 1969, 2035, 2901, 827, 1004],
 [1386, 3403, 699, 3504, 2991, 3936, 1654, 277, 2544, 2863],
 [2683, 3353, 3849, 1275, 3937, 827, 1135, 1081, 2317, 949, 827, 1842, 410],
 [1805, 1950, 2995, 3608, 1352, 559, 405, 2755, 3169, 1818, 176],
 [3851, 3936, 3700, 3839, 2945, 1180, 3059, 1412, 2428, 1009, 498, 3504, 2945],
 [1911, 935, 1415, 2533, 1218, 827, 1781, 2507, 1719],
 [1072, 2645, 1536, 3893, 827, 2544, 2863, 498, 1886, 887],
 [3504, 3776, 827, 3504, 271, 3936, 425, 902, 1038, 1744, 3090],
 [757, 2490, 3477, 1534, 1369, 1806, 781, 1946],
 [1381, 958, 3399, 3504, 1846, 877, 3504, 3446, 510, 2533, 3504, 2118],
 [316, 2277, 2945, 247, 3187, 3715, 1534, 1471, 2931, 686, 3585],
 [3249, 3115, 3881, 2945, 3523, 2281, 356, 3504, 3715, 1690, 3897],
 [473, 1518, 277, 1744, 219, 509, 2357, 2945, 145],
 [308, 763, 1431, 521, 2533, 535, 902, 1632, 277, 968],
 [1214, 2243, 2615, 3461, 566, 3936, 93, 599, 1800, 7, 498, 3504, 3817],
 [3851, 493, 2774, 2446, 1536, 575, 508, 781, 3280, 1746, 1688],
 [1795,
  1494,
  2293,
  1047,
  3936,
  2945,
  3426,
  2432,
  1536,
  2329,
  2166,
  3769,
  3936,
  1425],
 [1035, 1147, 2156, 2033, 2952, 3462, 2354, 1736, 3135],
 [1886, 3475, 3524, 3832, 498, 1438, 653, 2464, 3224, 1737],
 [3620, 1095, 1884, 709, 1534, 1254, 1946],
 [3952, 277, 597, 1675, 2533, 3654, 413, 3880, 902, 2588, 1473, 1985],
 [1179, 2916, 1264, 1478, 3705, 2037, 2519],
 [841, 827, 2210, 84, 2460, 1754, 3984, 2033, 913, 3063],
 [3263, 897, 2101, 1349, 1538, 498, 439, 902, 2311, 3303, 1082],
 [614, 1039, 176, 1776, 1026, 2198, 913, 380, 2945, 2214, 3498],
 [2059, 41, 3936, 410, 1737, 3197, 264, 2533, 2930, 3658],
 [3597,
  3351,
  272,
  1136,
  1000,
  1092,
  2508,
  2519,
  498,
  704,
  902,
  3303,
  3936,
  2780,
  3643,
  556],
 [1026, 2952, 902, 3504, 1528, 498, 1438, 653, 2464, 3224, 1261],
 [498, 2945, 1216, 3936, 3022, 3263, 897, 3326, 1082, 3936, 601, 3303],
 [788, 208, 488, 2952, 2075, 2646, 93, 376, 1536, 3269],
 [3149, 3353, 3504, 566, 3922, 858, 2312, 2585, 2945, 149, 2000, 1840],
 [1480, 2479, 2191, 3952, 277, 3327, 2533, 1183, 77, 3696, 3928, 1190],
 [1860, 2544, 2326, 1826, 2931, 709, 1357, 77],
 [897, 2944, 2780, 3643, 1108, 3944, 1551, 3936, 3813, 2775],
 [2780, 3643, 2340, 2274, 3657, 1536, 3952, 277, 2776, 2448, 700],
 [322, 2707, 3906, 1077, 277, 3564, 545, 3220, 149],
 [2876, 819, 2597, 3936, 705, 2571, 1056, 3906, 558, 2925],
 [564, 3920, 2880, 2723, 528, 2533, 2750, 498, 3452, 2945, 370, 2204],
 [2921,
  781,
  2521,
  3935,
  1262,
  2931,
  1287,
  3504,
  3303,
  827,
  2544,
  3906,
  3321,
  472],
 [3757, 655, 1163, 277, 710, 1634, 1835, 2931, 1077, 277, 397, 2115],
 [1633, 2923, 3878, 2367, 806, 1536, 4, 1845, 1694],
 [1077, 2061, 1634, 3537, 3915, 545, 3220, 498, 1026],
 [2562, 1547, 3713, 3063, 946, 3936, 1021, 1723, 3818, 3906, 3012, 1431],
 [1817, 1085, 680, 3580, 1617, 2452, 3613, 2461, 3984, 2953],
 [3178, 2495, 1467, 3512, 416, 142, 397, 757, 3504, 1021, 277, 3206],
 [2880, 152, 3936, 442, 3015, 508, 2168, 2533, 93, 1213, 3219, 172],
 [1512, 3500, 585, 1819, 2533, 1291, 3700, 498, 1969, 2035, 1004],
 [1851, 277, 1794, 505, 3936, 648, 3745, 3735, 277, 663, 1159, 1073],
 [2128, 2445, 2731, 2533, 1135, 1008, 3936, 93, 2441, 3224, 2151, 2157],
 [2994,
  2017,
  2048,
  3765,
  2585,
  3859,
  1886,
  2315,
  841,
  3316,
  841,
  2351,
  2006,
  3936,
  2583],
 [919, 2693, 3374, 3552, 1606, 2061, 2749, 2533, 3329, 277, 1528],
 [3298, 1050, 1534, 3551, 3637, 913, 468, 277, 372, 569],
 [3906, 1438, 1706, 1886, 498, 1703, 3906, 1002, 2931, 498, 896, 2184],
 [1756, 2522, 3083, 3109, 3965, 2747, 498, 2748, 827, 784, 1534, 2878, 1040],
 [731, 3969, 410, 3765, 259, 827, 2620, 902, 364, 2990, 1111],
 [3504, 3511, 2975, 2271, 2952, 566, 1508, 2533, 3504, 1744, 515],
 [528, 693, 3906, 1907, 248, 850, 3936, 92, 3634, 2631, 2893],
 [2631, 892, 902, 1182, 1077, 545, 3220, 3495, 82],
 [591, 2523, 1860, 3423, 7, 737, 3936, 52, 3440, 2329, 3391, 772],
 [2966, 2585, 2684, 1703, 3409, 3906, 1438, 2407, 498, 806],
 [2210,
  1356,
  662,
  2158,
  2658,
  1651,
  623,
  3570,
  2862,
  1565,
  3169,
  3614,
  1176,
  2610],
 [1886, 52, 655, 2544, 3256, 2952, 1617, 1875, 498, 1654],
 [904, 1497, 734, 827, 2062, 1526, 834, 1523, 3169, 3152, 2966],
 [7, 1437, 84, 2533, 166, 827, 1041, 2848, 2486, 498, 2104],
 [3952, 277, 3757, 3936, 2460, 494, 2005, 1558, 2931, 1579, 3779],
 [1547,
  3713,
  1073,
  3580,
  975,
  2345,
  3580,
  3794,
  3132,
  3728,
  280,
  841,
  293,
  391,
  1895,
  1521],
 [919, 1483, 827, 1181, 2341, 2585, 3466, 1081, 589, 2006, 1041, 3343],
 [2862, 1764, 235, 472, 425, 73, 319, 2424, 3856],
 [125, 856, 3939, 498, 806, 1540, 377],
 [2104, 1698, 549, 1555, 3029, 242, 1534, 3783, 3570],
 [3920, 1318, 3411, 756, 3656, 1079, 298, 3936, 2673, 3765, 1377],
 [2454, 1159, 2578, 1687, 498, 3144, 277, 1627],
 [1222,
  1149,
  655,
  1163,
  277,
  565,
  406,
  3936,
  1759,
  1895,
  1654,
  2077,
  3509,
  3477,
  2544,
  3700],
 [1004, 277, 805, 931, 3187, 2952, 1361, 3936, 3857, 831, 1189, 3936, 3450],
 [2104, 2683, 149, 1534, 3321, 2025, 7, 708],
 [1184, 1122, 1536, 651, 715, 890, 3133, 1089],
 [3504, 3689, 2077, 215, 498, 26, 6, 902, 3506, 128, 3984, 1109, 1081, 3118],
 [3785, 1667, 1168, 1886, 3516, 3936, 704, 3794, 2734],
 [3309, 3620, 867, 3684, 277, 3654, 1379, 3906, 2404, 3935, 3356, 1930],
 [2780, 2004, 1467, 2239, 1886, 498, 48, 2593, 846, 3785],
 [2412,
  827,
  3935,
  1556,
  2633,
  1371,
  924,
  2667,
  827,
  1257,
  3666,
  498,
  487,
  1283],
 [2742, 2441, 3224, 869, 1450, 1635, 3936, 521, 1339, 2096, 3087, 2570],
 [2562, 1435, 1656, 3481, 1041, 2578, 3132, 3709, 1826, 3936, 619],
 [2993, 3440, 3936, 911, 115, 277, 3558],
 [3684, 1320, 2533, 3146, 2460, 827, 3935, 3356, 1930, 2025, 3030, 3309, 3467],
 [3952, 277, 3232, 966, 498, 3016, 1536, 2771, 2909, 2888, 566, 2016],
 [2637,
  3715,
  2945,
  3492,
  3135,
  1471,
  2351,
  3515,
  1343,
  2165,
  3011,
  3796,
  1519],
 [3913, 963, 1971, 3636, 1270, 707, 2287],
 [3396, 1877, 1979, 2239, 3267, 1081, 1858, 2664, 2025, 1956, 1749, 842],
 [2945,
  835,
  445,
  776,
  1677,
  2952,
  304,
  3906,
  586,
  2383,
  277,
  3269,
  2967,
  2975,
  1111],
 [105, 2341, 3792, 841, 827, 1886, 2355, 3936, 1980, 478, 498, 806],
 [1650,
  2088,
  2458,
  93,
  223,
  3303,
  498,
  3504,
  3018,
  2945,
  2971,
  1219,
  2533,
  1101,
  433,
  827,
  3504,
  3066],
 [1605,
  2217,
  1977,
  277,
  2001,
  3925,
  3530,
  1111,
  1826,
  498,
  1513,
  827,
  1594,
  3906,
  3920,
  1749],
 [2535, 115, 277, 731, 3259, 253, 34, 2625, 2025, 2507, 3206],
 [2278, 857, 3920, 277, 1576, 827, 701, 1971],
 [2376, 1255, 1872, 1375, 3627, 3920, 3373, 701, 1971, 3906, 3452, 2945, 370],
 [1754, 3197, 3613, 2461, 1665, 521, 2585, 2507, 3984, 498, 953, 3874],
 [3911, 2347, 2533, 1141, 2155, 1103, 2194, 687, 3268],
 [1588,
  2916,
  963,
  108,
  1583,
  1270,
  1315,
  3906,
  953,
  1081,
  280,
  3936,
  2785,
  2585,
  1163],
 [3874, 2952, 2440, 2015, 3684, 946, 1781, 3356, 2658, 3936, 3146],
 [1599,
  2195,
  705,
  1081,
  1817,
  3920,
  3446,
  756,
  603,
  2470,
  2194,
  3942,
  1588,
  2204],
 [3504, 1736, 3246, 1809, 1280, 3080, 2098, 1041, 174, 827, 3953, 3406, 1294],
 [2435, 2500, 908, 2573, 225, 1637, 3104, 1123, 1081, 3622],
 [3918,
  1522,
  3559,
  3131,
  667,
  277,
  3116,
  1536,
  2507,
  1319,
  1265,
  50,
  93,
  2945,
  3361,
  3614,
  1775,
  3451],
 [3224,
  2405,
  1467,
  1748,
  2945,
  3545,
  962,
  3936,
  193,
  1998,
  3794,
  1163,
  2806,
  565,
  1918],
 [186, 924, 2870, 827, 889, 498, 1812, 2540, 3920, 2952, 2581, 913, 701, 1594],
 [2342, 3260, 277, 3108, 2027, 3936, 3734, 1175, 2369, 765, 3906, 1319],
 [1175, 2369, 2573, 3854, 1572, 1536, 3356, 152, 3906, 2640, 1319],
 [1081, 3504, 3252, 2533, 2543, 1310, 1319, 301, 892, 3936, 576, 3743],
 [1004, 715, 2488, 634, 259, 566, 498, 2791, 1324],
 [1377, 2640, 1319, 1916, 2916, 3982, 3504, 3878, 3593, 963, 481, 3936, 11],
 [2945, 251, 3947, 2181, 3029, 2588, 1249, 846, 1079, 1071, 3132, 3728],
 [1407, 468, 655, 2507, 1411, 277, 498, 235, 1852, 3580, 277, 498, 1067, 1114],
 [1067, 3479, 1354, 1559, 1446, 284, 2945, 1068, 3452, 2945, 370, 1946],
 [3686, 1703, 2903, 3365, 2893, 2667, 827, 3539, 503, 3169, 1975, 2794, 1946],
 [727, 2654, 904, 2713, 1513, 827, 2862, 2025, 1114, 3496, 1548, 2435],
 [3920, 3436, 2826, 2785, 913, 916, 3246, 3452, 2945, 370, 1095],
 [1588, 3396, 1562, 3493, 498, 2841, 2516, 3650, 498, 674, 1281, 3169, 3884],
 [2945, 3285, 3316, 3580, 1448, 2945, 2619, 3580, 3045, 2945, 2987, 487, 1440],
 [2329, 2380, 2060, 2854, 1480, 2734, 2405, 2533, 2340, 902, 1133],
 [335, 1872, 3316, 3019, 3814, 892, 1073, 498, 2305, 2173, 2337],
 [3452,
  2945,
  370,
  1095,
  1114,
  3920,
  2351,
  1825,
  3449,
  2543,
  827,
  2140,
  3906,
  231],
 [2954, 3920, 277, 1141, 2155, 952, 1412, 2385, 1604, 2700, 1329],
 [1820, 2104, 2806, 3317, 1189, 1173, 917, 2946, 2158, 827, 2945, 730, 99],
 [1588, 2664, 1041, 502, 1354, 3647, 2274, 2549, 3936, 3952, 277],
 [3332, 3775, 831, 1579, 3845, 3932, 2330, 3448, 1606],
 [457, 1040, 3906, 3671, 487, 3745, 3936, 3128, 498, 3796, 3365, 2533, 375],
 [190, 3388, 1289, 2738, 781, 498, 1089, 3001, 2204],
 [2560, 277, 1349, 1159, 3500, 3936, 3406, 913, 1160, 2989, 3321],
 [2104, 1108, 3601, 166, 2087, 3989, 6, 16, 731],
 [3129, 150, 2552, 2827, 498, 3935, 376, 1592, 1261, 1305, 2852],
 [1409, 222, 2191, 1915, 3049, 1261, 3936, 1514, 2214, 614, 2217, 2536],
 [1487,
  3816,
  2191,
  2674,
  3936,
  2673,
  902,
  594,
  190,
  767,
  506,
  1081,
  2507,
  1568,
  1523],
 [942, 2467, 3874, 1379, 2194, 2286, 3936, 1040, 3427, 3936, 739, 448],
 [3058, 1358, 3417, 3157, 897, 2087, 902, 133, 86],
 [3224,
  827,
  3504,
  532,
  2952,
  3462,
  2693,
  1690,
  2025,
  2543,
  2796,
  1195,
  3348,
  523],
 [2742, 1726, 2508, 3325, 2134, 498, 3983, 576, 2444],
 [3529, 210, 3577, 1635, 277, 2159, 1886, 3906, 2116],
 [1616, 499, 2211, 1461, 1521, 2952, 1035, 2810, 686, 3029, 2514],
 [1093,
  3430,
  3245,
  2063,
  827,
  2214,
  1081,
  3920,
  277,
  1478,
  2328,
  178,
  3936,
  3040,
  3745],
 [2025, 3268, 897, 3186, 3058, 1358, 3700, 2876, 2503],
 [2435, 2952, 3504, 1622, 3246, 827, 1886, 2982, 2525, 2852],
 [896, 1492, 3936, 779, 758, 1172, 902, 2242, 1616],
 [3844, 498, 3177, 277, 805, 7, 737, 2191, 902, 2033],
 [1077, 2780, 566, 827, 2329, 1297, 1281, 2164, 3757, 3355, 502],
 [1473, 3828, 1467, 2281, 2326, 1787, 3770, 509, 2953, 1409, 1217, 1483, 2870],
 [1159, 2826, 3774, 570, 2604, 1004, 277, 1817, 1134, 1290, 2542],
 [1246, 3570, 2562, 1737, 2267, 644, 932],
 [947, 1873, 3075, 3936, 782, 913, 3118, 902, 1869, 1306],
 [3436, 127, 3560, 44, 3715, 277, 2146, 109, 498, 3227],
 [2858, 1280, 1713, 3352, 277, 2946, 637, 3947, 2519, 3906, 1874],
 [532, 3214, 1001, 2964, 1927, 3906, 2945, 2183, 1534, 357, 1839],
 [1847, 498, 3830, 7, 1249, 277, 3874, 1462, 3936, 2991, 2329, 2444],
 [3332,
  1345,
  699,
  1902,
  1089,
  1413,
  902,
  3810,
  3979,
  2544,
  3936,
  298,
  498,
  2666],
 [2731, 3715, 1914, 699, 2357, 381, 1497, 827, 93, 223, 3876, 3309, 245, 3374],
 [828, 495, 783, 827, 947, 2722, 2519, 3906, 2869],
 [1714, 72, 655, 3580, 2356, 566, 2673, 701, 1971, 1895, 3580, 1085, 2183],
 [1639, 277, 1189, 2285, 2931, 2396, 2025, 1748, 2643, 2821, 2931, 733, 665],
 [3739, 3573, 730, 3806, 3024, 985, 594, 3947],
 [788, 3936, 1759, 2540, 1270, 3071, 2625, 2952, 2945, 3523, 706],
 [3766, 659, 2482, 736, 2460, 902, 2214, 772, 2945],
 [3551, 1089, 655, 3433, 1089, 704, 3303, 1000, 1005, 3936, 618],
 [1197, 99, 1251, 3700, 1151, 996, 498, 169, 1081, 3571, 2444],
 [3398, 3936, 3528, 3332, 3936, 3496, 3920, 1095, 3574, 1114],
 [1181, 1806, 3098, 678, 3090, 1466, 827, 3170, 3715, 913, 3925, 2439],
 [1213, 3274, 3770, 2077, 3509, 3551, 3900, 3936, 305, 3441, 527, 3849, 1073],
 [3920, 3586, 3759, 3936, 1197, 2134, 521, 2604, 734],
 [915, 3164, 591, 1534, 809, 2533, 3643, 99, 3215],
 [1714, 1081, 3504, 3122, 3806, 827, 3162, 2877],
 [2309, 902, 1035, 3164, 2451, 745],
 [1677, 1149, 3936, 2243, 241, 1534, 2873, 2985, 498, 2599],
 [2393, 665, 2724, 913, 1797, 566, 2137, 913, 3793, 3244, 255, 514],
 [747, 47, 3936, 3667, 3426, 1050, 1523, 2533, 3343],
 [2742, 806, 625, 2581, 2025, 3604, 361, 1525, 2799, 1073],
 [2682, 1238, 1163, 2952, 1060, 1228, 3735, 1907, 2088],
 [791, 1345, 699, 1872, 3001, 3984, 267, 498, 958, 3936, 1409, 1139, 1817],
 [2591, 29, 305, 498, 242, 498, 2015, 675, 517, 3936, 666, 2260],
 [3504, 3057, 380, 416, 1880, 509, 1409, 3815, 827, 2303, 3770, 809, 3379],
 [3935, 2330, 2573, 2854, 1472, 102, 2533, 3982, 498, 3903],
 [372, 3936, 1381, 1534, 3928, 2522, 2604, 2243, 3461],
 [2265, 2776, 3159, 3090, 700, 2164, 3059, 64],
 [186, 924, 1527, 521, 498, 1089, 3001, 2204, 3332, 655],
 [3796, 1819, 2311, 1325, 3318, 3707, 2519, 3906, 3653],
 [1754, 1951, 498, 2486, 3906, 861, 3814, 2505, 3711, 1711, 1182, 953],
 [1501, 1238, 2470, 2326, 335, 2552, 2056, 2281],
 [2213, 17, 575, 508, 277, 1354, 811, 1466],
 [3087, 2482, 498, 3613, 2461, 2356, 3874, 3936, 3218, 498, 953],
 [3423, 904, 3126, 1342, 498, 761, 953, 1686, 2486],
 [3115, 3384, 1595, 3132, 259, 3928, 558, 989, 1634, 3765, 546],
 [3849, 1703, 3906, 2583, 3781, 498, 192, 3409, 1678],
 [727, 699, 1645, 3765, 2945, 1035, 3828, 3792, 623, 2548, 3163, 498, 2195],
 [2552, 2056, 902, 3504, 119, 3936, 3186, 3729, 655],
 [3955, 1803, 3906, 1883, 2967, 3409, 2585, 1820, 566, 2355],
 [205, 3731, 2025, 2932, 3936, 3983, 2376, 2683, 356, 7, 3904],
 [2122, 989, 306, 3909, 1604, 917, 3345, 2264, 902, 2239],
 [730, 3806, 809, 1322, 1626, 1041, 1887, 3936, 547, 2806, 710],
 [2549, 498, 2056, 1897, 3325, 566, 2134, 1536, 1827, 1408, 1535],
 [3739, 2355, 2583, 3148, 3714, 3968, 1610, 3936, 1879, 2608],
 [3312, 2298, 3865, 915, 3164, 2214, 3936, 3982, 3504, 3327, 841, 3509, 2607],
 [913, 2407, 6, 1888, 2533, 2815, 1849, 35, 330, 293, 3952, 277],
 [2923, 457, 498, 3012, 277, 1349, 2840, 2302, 3964],
 [1886, 597, 670, 1998, 1197, 3936, 2785, 7, 3936, 3176, 597],
 [1677, 425, 3537, 2584, 1218, 3236, 2533, 2873, 901],
 [201, 730, 1536, 1173, 1932, 1251, 1454, 498, 991, 103, 87],
 [3209, 236, 655, 3969, 672, 498, 3504, 3545, 509, 2357, 2507, 678, 2032],
 [3849, 1644, 3396, 2795, 2444, 3202, 3936, 149, 2204],
 [3952, 277, 3511, 206, 3232, 3936, 3358, 3578, 2164, 3329],
 [1473, 3828, 3052, 3296, 1287, 3614, 2533, 3504, 2015, 3066, 498, 1035, 2664],
 [1536, 3263, 897, 2191, 3068, 652, 2452, 3512, 2533, 3928, 3224, 3435],
 [2239, 277, 2399, 1462, 1412, 1710, 3742, 2533, 2297, 3066, 498, 1754, 1183],
 [1817, 3925, 2703, 3306, 2533, 2333, 3397, 535, 902, 3152, 1534, 987],
 [993, 2111, 659, 2025, 1676, 2931, 3705, 975],
 [3710, 92, 3936, 3384, 1040, 902, 163, 2025, 731],
 [3433, 1089, 704, 3303, 731, 3936, 2357, 3260, 3169, 2283, 3087],
 [3627,
  3504,
  1369,
  821,
  1914,
  699,
  1073,
  3197,
  2585,
  3504,
  3452,
  2945,
  370,
  842],
 [3512, 3442, 1515, 1345, 699, 521, 2685, 498, 1089, 3001, 2204],
 [2635,
  3938,
  3127,
  788,
  3580,
  3040,
  2507,
  3303,
  1516,
  2753,
  1419,
  277,
  1228,
  3765,
  1716],
 [3332,
  1754,
  2522,
  2945,
  3230,
  3170,
  3263,
  3461,
  1348,
  1914,
  699,
  1336,
  498,
  835,
  740],
 [380, 410, 2977, 2025, 686, 2817, 2533, 3426, 3614, 2512, 6],
 [1754, 1886, 498, 2486, 3906, 594, 908, 3433, 2532],
 [3920,
  3937,
  3783,
  3308,
  498,
  1010,
  1773,
  1303,
  699,
  1645,
  1500,
  2533,
  2104,
  2371],
 [186, 924, 3583, 2533, 2945, 3391, 3906, 1621, 2414],
 [2643, 1159, 2037, 2225, 827, 3468, 2506, 498, 3369, 827, 210, 3775],
 [1645,
  902,
  1121,
  3627,
  1886,
  1085,
  3876,
  2264,
  2610,
  2158,
  827,
  3504,
  597,
  670,
  1998],
 [788, 3936, 3951, 1212, 3504, 2272, 908, 3064, 1149, 3936, 3938, 1225],
 [1218, 1251, 498, 3504, 2945, 144, 2533, 3397, 28, 566, 144, 2533, 3767],
 [2365, 2384, 277, 3115, 3384, 1189, 1041, 3031, 1534, 2604, 1839],
 [3504, 651, 3388, 2274, 1462, 2533, 3496, 3495, 1906, 845, 277, 3117],
 [897, 963, 784, 1534, 210, 1823, 2025, 2643, 2864],
 [1159, 2945, 3947, 269, 1754, 1281, 498, 650, 2033, 1182, 2441, 3224],
 [913, 902, 1951, 1975, 3396, 498, 1291, 1246, 1440, 2764, 1703],
 [517, 3911, 2177, 2533, 3197, 398, 917, 1898, 2931, 3365, 715],
 [2613, 2219, 2027, 3936, 3437, 2225, 827, 65, 1264, 1471, 1534, 2982, 3839],
 [2643, 1159, 1759, 210, 1823, 3936, 2357, 1193, 2194, 405, 827, 672],
 [1525,
  3947,
  749,
  1842,
  3073,
  3936,
  2583,
  1080,
  827,
  210,
  281,
  2528,
  498,
  3170],
 [3935,
  376,
  343,
  3008,
  498,
  1035,
  2907,
  756,
  404,
  2735,
  188,
  153,
  1910,
  498,
  1749],
 [2435, 2952, 3504, 2543, 2998, 3246, 827, 3504, 1592, 2094, 118, 3851],
 [2214,
  2255,
  3423,
  3936,
  432,
  2158,
  558,
  2954,
  3920,
  3700,
  1212,
  2540,
  3580,
  277,
  3938],
 [1615, 3794, 2945, 3737, 3508, 2945, 1442, 3942, 1588, 3299, 498, 414],
 [1035,
  1886,
  1342,
  1951,
  498,
  3826,
  1860,
  3423,
  704,
  2025,
  2171,
  3468,
  481,
  1916,
  1537],
 [290,
  3302,
  1001,
  2993,
  2533,
  3796,
  277,
  482,
  2312,
  3580,
  277,
  391,
  3936,
  3760,
  1534,
  3952,
  277],
 [3705, 1943, 413, 3925, 3169, 2739, 937, 1151, 2952, 536, 2945, 1879, 1325],
 [1712, 2373, 1732, 3639, 3601, 498, 133, 2174, 277, 788, 3936, 3980, 1163],
 [1067, 1986, 3614, 1726, 1454, 498, 3983, 576, 2486, 2688],

In [11]:
input_padding=pad_sequences(one_hot_input, maxlen=max_len_input, padding='post')
input_padding

array([[ 913, 3614, 1523, ...,    0,    0,    0],
       [1228, 1553, 1284, ...,    0,    0,    0],
       [3586,  827, 3504, ...,    0,    0,    0],
       ...,
       [2682,  277, 1939, ...,    0,    0,    0],
       [1478, 2560, 3443, ...,    0,    0,    0],
       [2780, 1886, 2407, ...,    0,    0,    0]], dtype=int32)

In [12]:

from keras.layers import Embedding, LSTM, Input

encoder_inputs = Input(shape=(None,))
embedding_layer = Embedding(input_dim=len(unique_words_input), output_dim=256)
encoder_embeddings = embedding_layer(encoder_inputs)
encoder_outputs, state_h, state_c = LSTM(256, return_state=True)(encoder_embeddings)

2025-09-02 11:50:52.532236: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

# Output Preprocessing

In [13]:
corpus1 = []
for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['French'][i])
    review = review.lower()
    review = review.split()

    review = ' '.join(review)
    corpus1.append(review)

In [14]:
decoder_input_data = ["<start> " + txt + "" for txt in corpus1]
decoder_target_data= ["" + txt + " <end>" for txt in corpus1]
decoder_input_data

['<start> health experts said it is too early to predict whether demand would match up with the 171 million doses of the new boosters the u s ordered for the fall',
 '<start> he was subdued by passengers and crew when he fled to the back of the aircraft after the confrontation according to the u s attorney s office in los angeles',
 '<start> until you have a dog you don t understand what could be eaten',
 '<start> accidentally put grown up toothpaste on my toddler s toothbrush and he screamed like i was cleaning his teeth with a carolina reaper dipped in tabasco sauce',
 '<start> amy cooper accused investment firm franklin templeton of unfairly firing her and branding her a racist after video of the central park encounter went viral',
 '<start> the 63 year old woman was seen working at the south carolina store on thursday she was found dead monday after her family reported her missing authorities said',
 '<start> who s that behind you an anchor for new york s pix11 asked journalist michelle ross as she finished up an interview',
 '<start> more than half a million people remained without water service three days after the storm lashed the u s territory',
 '<start> in mija director isabel castro combined music documentaries with the style of euphoria and clueless to tell a more nuanced immigration story',
 '<start> white house officials say the crux of the president s visit to the u n this year will be a full throated condemnation of russia and its brutal war',
 '<start> fifa has come under pressure from several european soccer federations who want to support a human rights campaign against discrimination at the world cup',
 '<start> the incident underscores a growing wave of protests against the funeral for shinzo abe who was one of the most divisive leaders in postwar japanese politics',
 '<start> hurricane fiona lashed the turks and caicos islands and was forecast to squeeze past bermuda later this week',
 '<start> one man s claims that he scammed people on the platform caused several popular streamers to consider a twitch boycott',
 '<start> conservative activist virginia thomas the wife of supreme court justice clarence thomas has agreed to participate in a voluntary interview with the house panel investigating the jan 6 insurrection',
 '<start> polyakov s record breaking trip to outer space saw him orbit earth 7 075 times and travel nearly 187 million miles',
 '<start> starring keegan michael key judy greer and johnny knoxville the hulu show follows the revival of a fictional early 2000s sitcom',
 '<start> maury wills who helped the los angeles dodgers win three world series titles with his base stealing prowess has died',
 '<start> the concerted and quickening kremlin backed efforts to swallow up four regions could set the stage for moscow to escalate the war',
 '<start> the turks and caicos islands government imposed a curfew as the intensifying storm kept dropping copious rain over the dominican republic and puerto rico',
 '<start> for the past 18 months hollywood has effectively boycotted the globes after reports that the hfpa s 87 members of non american journalists included no black members',
 '<start> president issues vow as tensions with china rise',
 '<start> the storm knocked out the power grid and unleashed floods and landslides in puerto rico where the governor said the damage was catastrophic',
 '<start> the single engine plane was participating in the national championship air races on sunday when it crashed into a field killing the pilot officials said',
 '<start> an annual celebration took on a different feel as russia s invasion dragged into day 206',
 '<start> mark frerichs a navy veteran and civilian contractor was kidnapped in afghanistan in january 2020',
 '<start> las vegas never had a professional sports champion until sunday',
 '<start> president joe biden and first lady jill biden were among thousands of mourners from locals and tourists to royals and world leaders to pay their respects',
 '<start> the avatar director said aspects of his 2009 movie are still competitive with everything that s out there these days',
 '<start> alain robert known as the french spider man has climbed the burj khalifa and the empire state building',
 '<start> u s president joe biden in london for the funeral of queen elizabeth ii says his heart went out to the royal family adding the queen s death left a giant hole',
 '<start> despite entering false information their work wasn t redone fully and in some cases the census takers received bonuses the office of inspector general reported',
 '<start> on monday the world s first public database of fossil fuel production reserves and emissions launches',
 '<start> the 19 year old reportedly fled into the thames in a failed bid to escape police',
 '<start> in 10 years people will be referring to the september 2022 storm as a benchmark storm',
 '<start> puerto rico was under a hurricane watch saturday as the storm barreled towards the u s territory',
 '<start> the world health organization is raising the alarm about a second disaster in the wake of the deadly floods in pakistan this summer as doctors and medical workers on the ground race to battle outbreaks of waterborne and other diseases',
 '<start> studies have repeatedly shown that ending public administration of water supplies doesn t work but that s now on the table in mississippi',
 '<start> never in the history of the duesseldorf customs office has a trail of slime led us to smuggled goods spokesman michael walk told the media',
 '<start> the director of the original 1982 film joins a writer of the 2017 sequel for the newest installment in the sci fi franchise',
 '<start> republican outrage over the shoddy u s withdrawal from afghanistan hasn t spurred support for resettling refugees',
 '<start> sarah collins rudolph lost an eye and has pieces of glass inside her body from a ku klux klan bombing that killed her sister and three other black girls inside an alabama church 59 years ago',
 '<start> a boil water advisory has been lifted for mississippi s capital and the state will stop handing out free bottled water on saturday',
 '<start> the phantom of the opera broadway s longest running show is scheduled to close in february 2023 a victim of post pandemic softening in theater attendance in new york',
 '<start> the former white house chief of staff has turned over records as part of a federal investigation into the jan 6 2021 assault on the capitol',
 '<start> the colombian american author s new book lightlark was rejected numerous times until she went directly to her readers for support',
 '<start> mykel gordon rushed to the woman s aid and held down her assailant until police arrived remarkably this wasn t the first time gordon may have saved a life',
 '<start> the oscar winner said she worked out for five hours a day for her role in the new action movie',
 '<start> the reality star told james corden she s branching out because clearly it s not working whatever i m doing',
 '<start> the las vegas podcasters are hoping to find out who shot the rap icon 26 years ago',
 '<start> the grammy winning rapper surprised star struck children at the alexander macomb school in morris heights to make the announcement',
 '<start> richardson the former u s ambassador to the united nations and a frequent emissary in hostage negotiations held meetings with russian leaders',
 '<start> the television awards ceremony lost roughly 1 5 million viewers compared to its 2021 program',
 '<start> white house press secretary karine jean pierre said a rail shutdown is not acceptable and would harm families as well as businesses',
 '<start> the state s general treasurer is slated to face former cranston mayor allan fung r in the general election',
 '<start> a u s firm that monitors false online claims reports that searches for information about prominent news topics on tiktok are likely to turn up results riddled with misinformation',
 '<start> on a monthly basis prices rose 0 1 after a flat reading in july',
 '<start> the director was best known for the groundbreaking movie breathless',
 '<start> they re pressing for salary increases they say will help improve patient care by resolving understaffing stresses that have worsened in the pandemic',
 '<start> cancer does not discriminate red and blue the president said monday beating cancer is something we can do together',
 '<start> who we have on the field is who we re gonna play scott told fox news sunday',
 '<start> the race s organizers say nonbinary athletes won t have to register with the men s or women s divisions and provided qualifying times to guide their training',
 '<start> varvaro pitched mostly with the atlanta braves and started his law enforcement career in 2016',
 '<start> democrats in the state s more moderate house district are deciding who will take on a popular republican former mayor',
 '<start> biden plans to draw attention to a new federally backed study that seeks to validate using blood tests to screen against multiple cancers',
 '<start> the research based artist has found dynamic ways to confront conversations about female empowerment motherhood and labor in her artwork',
 '<start> it s not about sensationalizing or even tarnishing the reputation of sidney poitier rather the new documentary honors his humanity every facet of it',
 '<start> carlos alcaraz defeated casper ruud in the u s open final to earn his first grand slam at age 19 and become the youngest man to move up to no 1 in the rankings',
 '<start> firefighters made progress against a huge northern california wildfire that was still growing and threatening thousands of mountain homes',
 '<start> president joe biden has marked the 21st anniversary of the sept 11 attacks taking part in a somber wreath laying ceremony held at the pentagon under a steady rain',
 '<start> september 11th remains a point for reflection on the 2001 attacks that reconfigured national security policy and spurred a u s war on terror worldwide',
 '<start> the plant one of the 10 biggest atomic power stations in the world has been occupied by russian forces since early in the war which marked its 200th day on sunday',
 '<start> visa s adoption is significant as the largest payment network and will likely add pressure for mastercard and american express to adopt the code as well',
 '<start> the justice department proposed two retired judges for the role trump s team proposed a retired judge and a lawyer',
 '<start> the director told the audience he was super excited to be finally finishing up movie two as he has three additional installments in the works',
 '<start> russia s defense ministry announced that troops will be pulled back in two area where a ukrainian counter offensive has made significant advances',
 '<start> after a 10 day heat wave that nearly overwhelmed the electrical grid southern california got cooler weather but also a ferocious tropical storm',
 '<start> ukrainian forces are claiming new success in their counteroffensive against russian forces in the east',
 '<start> please join me in a round of applause for 70 years of service the pop star told the crowd after he paused his madison square garden performance',
 '<start> derrell mcdavid s testimony could be a major blow to the r b singer s hope of acquittal',
 '<start> both british and international newspapers honor the passing of the u k s longest reigning monarch',
 '<start> the 19 year old singer dancer and youtube icon will receive the 2022 gamechanger award for her focus on anti bullying efforts',
 '<start> speaking from islamabad antonio guterres said countries bearing more responsibility for climate change should have faced this challenge',
 '<start> clark county public administrator robert telles was arrested in the fatal stabbing of jeff german who had been investigating his office',
 '<start> the internet ignited in approval over the former first lady s hairstyle choice for the monumental day',
 '<start> the actor said he was so badly concussed while shooting the series finale that he feared for his life and was holding onto the walls while recovering',
 '<start> opponents of the measure claimed typos made the qualifying petitions incomprehensible but the state s highest court rejected that argument',
 '<start> the lawsuit says allowing homeless people s tents to block city sidewalks makes it difficult for people using wheelchairs walkers or canes to use them',
 '<start> the fire in thuan an city began late tuesday and trapped both workers and customers inside the multi story venue',
 '<start> the mlb players association will finally be a member of the afl cio affiliating with 57 other unions across industries',
 '<start> in most of the 200 scripted shows that researchers analyzed muslim characters were typically violent dehumanized or disparaged if they existed at all',
 '<start> states are cutting back and congress is unlikely to step in even after the pandemic exposed the unemployment system s shortcomings',
 '<start> airport officials in austin texas say an early morning power outage is causing flight delays even as electricity has been restored',
 '<start> the head of the international atomic energy agency warned the u n security council that something very very catastrophic could take place at zaporizhzhia',
 '<start> such attacks have become a growing threat to u s schools with several high profile incidents reported since last year',
 '<start> a second fire killed two people in northern california this weekend',
 '<start> the detroit tigers rookie utility player got pressed into relief pitching duty in a 10 0 loss to the angels',
 '<start> the city remains under a boil water notice which first went into effect on july 30',
 '<start> the social media giant was fined for violations of data privacy laws related to information about children on instagram',
 '<start> there is new high fencing around the texas community s public schools that still isn t finished and a heavy police patrol that many families don t trust',
 '<start> the finding comes after the biden administration confirmed that the russian military in august took delivery of iranian manufactured drones for use in ukraine',
 '<start> the as it was singer said he also doesn t see many parallels between music and acting',
 '<start> jocelyn benson said misinformation fuels the potential for additional threats harassment and even violence on election day',
 '<start> cloudflare ceo matthew prince had previously resisted calls to block the site',
 '<start> he s welcome in my yard as long as he doesn t kill me or my family the homeowner quipped',
 '<start> when elsa avila looks at the scar that runs down her torso she can t help remember may 24 when a gunman stormed her fourth grade wing at robb elementary in uvalde texas killing 19 children and two teachers and leaving her and others wounded',
 '<start> tim michels calls on supporters to go after media following milwaukee journal sentinel story reporting multimillionaire s donations to anti abortion groups',
 '<start> police in tennessee say an arrest has been made in the disappearance of a woman who was abducted while jogging',
 '<start> residents of mississippi s majority black capital still don t have clean water after rains worsened the existing infrastructure',
 '<start> authorities warn that more flooding is expected as lake manchar swells from unprecedented monsoon rains that have killed nearly 1 300 people',
 '<start> students who survived the may 24 shooting at robb elementary in texas are spending the summer with a host of mental health issues including ptsd',
 '<start> thunderstorms and heavy rain pounded parts of northwest georgia on sunday sparking flash flooding and dangerously high waters in some areas',
 '<start> millennials might remember the family s mtv reality series from the early 2000s the bbc series will be filmed at the 350 acre osbourne estate in england',
 '<start> a pilot has been arrested after circling a small airplane over tupelo mississippi while threatening to crash into a walmart store',
 '<start> part of the space agency s artemis program the rocket is the most powerful to date',
 '<start> tragic toll followed hazardous crossing by desperate dozens said officials',
 '<start> nashua police charged chanphanou sab pou with three misdemeanor counts of violation of privacy he could face up to one year in jail for each charge',
 '<start> cipollone s former deputy patrick philbin is also reportedly scheduled to provide testimony to the grand jury on friday',
 '<start> the storm the first hurricane of an unusually quiet storm season is centered about 885 miles west of the azores',
 '<start> the low key funeral reflects the kremlin s uneasiness about the legacy of gorbachev who is despised by many at home for the collapse of the soviet union',
 '<start> the inaugural flight of the 322 foot artemis i rocket the most powerful ever built by nasa was delayed late in the countdown monday',
 '<start> the unemployment rate rose to 3 7 from a half century low of 3 5 in july as more americans came off the sidelines to look for jobs',
 '<start> brandy bottone had referred to roe v wade and texas penal code which identifies an unborn child as an individual when she was first stopped for using the lane',
 '<start> if your freezer is overflowing or you re tired of carrying around ice packs and bottles of pumped milk this option could be for you',
 '<start> the nun was held by kidnappers for nearly five months following an armed raid of her burkina faso home',
 '<start> the plaque shows a hooded man holding a weapon',
 '<start> the unprecedented red tide is creating a foul odor that may get worse during the oncoming heat wave',
 '<start> the stay i missed you artist reflects on pushing against a culture where female singer songwriters were expected to fit a certain mold to make it big',
 '<start> the 36 page filing described how trump and his representatives did not hand over classified materials at the property',
 '<start> the soviet union s last leader reportedly earned nearly 1 million even though he refused to eat the pizza on camera',
 '<start> the gop is continuing to contort itself in defense of donald trump despite new information relating to classified documents held at his florida estate',
 '<start> these are the biggest secrets in the world steve doocy said in response to the ex president keeping top secret documents at his private residence',
 '<start> prosecutors rested their case against the singer who stands accused of producing child sexual abuse videos in his latest trial',
 '<start> it s one thing after another for donald trump s problem plagued truth social',
 '<start> beyond toothaches there are other common red flags that you re dealing with nighttime teeth grinding',
 '<start> we re going to play all nine innings here the artemis mission manager said after the first launch was scrubbed',
 '<start> ornato who at one point served as a white house political adviser is said to have witnessed trump lunge at a secret service agent during the capitol attack',
 '<start> hbo will release a six part follow up to the series beginning in october about the infamous sex cult led by keith raniere',
 '<start> moms with dysphoric milk ejection reflex d mer feel an intense but brief wave of depression anxiety or other negative emotion before letdown and it s more common than you might think',
 '<start> the tiktok star s mom sheri easterling and the betty rapper made their romance public but her ex monty lopez is not happy about it',
 '<start> house members are only supposed to use proxy voting when they cannot be present due to covid 19 but that s not stopping representatives from voting remotely on the campaign trail',
 '<start> most republicans including me believe when it comes to trump there is no law graham said on fox news it s all about getting him',

In [15]:
words1=[]
for sent in corpus1:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words1.append(simple_preprocess(sent))
words1

[['health',
  'experts',
  'said',
  'it',
  'is',
  'too',
  'early',
  'to',
  'predict',
  'whether',
  'demand',
  'would',
  'match',
  'up',
  'with',
  'the',
  'million',
  'doses',
  'of',
  'the',
  'new',
  'boosters',
  'the',
  'ordered',
  'for',
  'the',
  'fall'],
 ['he',
  'was',
  'subdued',
  'by',
  'passengers',
  'and',
  'crew',
  'when',
  'he',
  'fled',
  'to',
  'the',
  'back',
  'of',
  'the',
  'aircraft',
  'after',
  'the',
  'confrontation',
  'according',
  'to',
  'the',
  'attorney',
  'office',
  'in',
  'los',
  'angeles'],
 ['until',
  'you',
  'have',
  'dog',
  'you',
  'don',
  'understand',
  'what',
  'could',
  'be',
  'eaten'],
 ['accidentally',
  'put',
  'grown',
  'up',
  'toothpaste',
  'on',
  'my',
  'toddler',
  'toothbrush',
  'and',
  'he',
  'screamed',
  'like',
  'was',
  'cleaning',
  'his',
  'teeth',
  'with',
  'carolina',
  'reaper',
  'dipped',
  'in',
  'tabasco',
  'sauce'],
 ['amy',
  'cooper',
  'accused',
  'investment',
  'firm',
  'franklin',
  'templeton',
  'of',
  'unfairly',
  'firing',
  'her',
  'and',
  'branding',
  'her',
  'racist',
  'after',
  'video',
  'of',
  'the',
  'central',
  'park',
  'encounter',
  'went',
  'viral'],
 ['the',
  'year',
  'old',
  'woman',
  'was',
  'seen',
  'working',
  'at',
  'the',
  'south',
  'carolina',
  'store',
  'on',
  'thursday',
  'she',
  'was',
  'found',
  'dead',
  'monday',
  'after',
  'her',
  'family',
  'reported',
  'her',
  'missing',
  'authorities',
  'said'],
 ['who',
  'that',
  'behind',
  'you',
  'an',
  'anchor',
  'for',
  'new',
  'york',
  'pix',
  'asked',
  'journalist',
  'michelle',
  'ross',
  'as',
  'she',
  'finished',
  'up',
  'an',
  'interview'],
 ['more',
  'than',
  'half',
  'million',
  'people',
  'remained',
  'without',
  'water',
  'service',
  'three',
  'days',
  'after',
  'the',
  'storm',
  'lashed',
  'the',
  'territory'],
 ['in',
  'mija',
  'director',
  'isabel',
  'castro',
  'combined',
  'music',
  'documentaries',
  'with',
  'the',
  'style',
  'of',
  'euphoria',
  'and',
  'clueless',
  'to',
  'tell',
  'more',
  'nuanced',
  'immigration',
  'story'],
 ['white',
  'house',
  'officials',
  'say',
  'the',
  'crux',
  'of',
  'the',
  'president',
  'visit',
  'to',
  'the',
  'this',
  'year',
  'will',
  'be',
  'full',
  'throated',
  'condemnation',
  'of',
  'russia',
  'and',
  'its',
  'brutal',
  'war'],
 ['fifa',
  'has',
  'come',
  'under',
  'pressure',
  'from',
  'several',
  'european',
  'soccer',
  'federations',
  'who',
  'want',
  'to',
  'support',
  'human',
  'rights',
  'campaign',
  'against',
  'discrimination',
  'at',
  'the',
  'world',
  'cup'],
 ['the',
  'incident',
  'underscores',
  'growing',
  'wave',
  'of',
  'protests',
  'against',
  'the',
  'funeral',
  'for',
  'shinzo',
  'abe',
  'who',
  'was',
  'one',
  'of',
  'the',
  'most',
  'divisive',
  'leaders',
  'in',
  'postwar',
  'japanese',
  'politics'],
 ['hurricane',
  'fiona',
  'lashed',
  'the',
  'turks',
  'and',
  'caicos',
  'islands',
  'and',
  'was',
  'forecast',
  'to',
  'squeeze',
  'past',
  'bermuda',
  'later',
  'this',
  'week'],
 ['one',
  'man',
  'claims',
  'that',
  'he',
  'scammed',
  'people',
  'on',
  'the',
  'platform',
  'caused',
  'several',
  'popular',
  'streamers',
  'to',
  'consider',
  'twitch',
  'boycott'],
 ['conservative',
  'activist',
  'virginia',
  'thomas',
  'the',
  'wife',
  'of',
  'supreme',
  'court',
  'justice',
  'clarence',
  'thomas',
  'has',
  'agreed',
  'to',
  'participate',
  'in',
  'voluntary',
  'interview',
  'with',
  'the',
  'house',
  'panel',
  'investigating',
  'the',
  'jan',
  'insurrection'],
 ['polyakov',
  'record',
  'breaking',
  'trip',
  'to',
  'outer',
  'space',
  'saw',
  'him',
  'orbit',
  'earth',
  'times',
  'and',
  'travel',
  'nearly',
  'million',
  'miles'],
 ['starring',
  'keegan',
  'michael',
  'key',
  'judy',
  'greer',
  'and',
  'johnny',
  'knoxville',
  'the',
  'hulu',
  'show',
  'follows',
  'the',
  'revival',
  'of',
  'fictional',
  'early',
  'sitcom'],
 ['maury',
  'wills',
  'who',
  'helped',
  'the',
  'los',
  'angeles',
  'dodgers',
  'win',
  'three',
  'world',
  'series',
  'titles',
  'with',
  'his',
  'base',
  'stealing',
  'prowess',
  'has',
  'died'],
 ['the',
  'concerted',
  'and',
  'quickening',
  'kremlin',
  'backed',
  'efforts',
  'to',
  'swallow',
  'up',
  'four',
  'regions',
  'could',
  'set',
  'the',
  'stage',
  'for',
  'moscow',
  'to',
  'escalate',
  'the',
  'war'],
 ['the',
  'turks',
  'and',
  'caicos',
  'islands',
  'government',
  'imposed',
  'curfew',
  'as',
  'the',
  'intensifying',
  'storm',
  'kept',
  'dropping',
  'copious',
  'rain',
  'over',
  'the',
  'dominican',
  'republic',
  'and',
  'puerto',
  'rico'],
 ['for',
  'the',
  'past',
  'months',
  'hollywood',
  'has',
  'effectively',
  'boycotted',
  'the',
  'globes',
  'after',
  'reports',
  'that',
  'the',
  'hfpa',
  'members',
  'of',
  'non',
  'american',
  'journalists',
  'included',
  'no',
  'black',
  'members'],
 ['president', 'issues', 'vow', 'as', 'tensions', 'with', 'china', 'rise'],
 ['the',
  'storm',
  'knocked',
  'out',
  'the',
  'power',
  'grid',
  'and',
  'unleashed',
  'floods',
  'and',
  'landslides',
  'in',
  'puerto',
  'rico',
  'where',
  'the',
  'governor',
  'said',
  'the',
  'damage',
  'was',
  'catastrophic'],
 ['the',
  'single',
  'engine',
  'plane',
  'was',
  'participating',
  'in',
  'the',
  'national',
  'championship',
  'air',
  'races',
  'on',
  'sunday',
  'when',
  'it',
  'crashed',
  'into',
  'field',
  'killing',
  'the',
  'pilot',
  'officials',
  'said'],
 ['an',
  'annual',
  'celebration',
  'took',
  'on',
  'different',
  'feel',
  'as',
  'russia',
  'invasion',
  'dragged',
  'into',
  'day'],
 ['mark',
  'frerichs',
  'navy',
  'veteran',
  'and',
  'civilian',
  'contractor',
  'was',
  'kidnapped',
  'in',
  'afghanistan',
  'in',
  'january'],
 ['las',
  'vegas',
  'never',
  'had',
  'professional',
  'sports',
  'champion',
  'until',
  'sunday'],
 ['president',
  'joe',
  'biden',
  'and',
  'first',
  'lady',
  'jill',
  'biden',
  'were',
  'among',
  'thousands',
  'of',
  'mourners',
  'from',
  'locals',
  'and',
  'tourists',
  'to',
  'royals',
  'and',
  'world',
  'leaders',
  'to',
  'pay',
  'their',
  'respects'],
 ['the',
  'avatar',
  'director',
  'said',
  'aspects',
  'of',
  'his',
  'movie',
  'are',
  'still',
  'competitive',
  'with',
  'everything',
  'that',
  'out',
  'there',
  'these',
  'days'],
 ['alain',
  'robert',
  'known',
  'as',
  'the',
  'french',
  'spider',
  'man',
  'has',
  'climbed',
  'the',
  'burj',
  'khalifa',
  'and',
  'the',
  'empire',
  'state',
  'building'],
 ['president',
  'joe',
  'biden',
  'in',
  'london',
  'for',
  'the',
  'funeral',
  'of',
  'queen',
  'elizabeth',
  'ii',
  'says',
  'his',
  'heart',
  'went',
  'out',
  'to',
  'the',
  'royal',
  'family',
  'adding',
  'the',
  'queen',
  'death',
  'left',
  'giant',
  'hole'],
 ['despite',
  'entering',
  'false',
  'information',
  'their',
  'work',
  'wasn',
  'redone',
  'fully',
  'and',
  'in',
  'some',
  'cases',
  'the',
  'census',
  'takers',
  'received',
  'bonuses',
  'the',
  'office',
  'of',
  'inspector',
  'general',
  'reported'],
 ['on',
  'monday',
  'the',
  'world',
  'first',
  'public',
  'database',
  'of',
  'fossil',
  'fuel',
  'production',
  'reserves',
  'and',
  'emissions',
  'launches'],
 ['the',
  'year',
  'old',
  'reportedly',
  'fled',
  'into',
  'the',
  'thames',
  'in',
  'failed',
  'bid',
  'to',
  'escape',
  'police'],
 ['in',
  'years',
  'people',
  'will',
  'be',
  'referring',
  'to',
  'the',
  'september',
  'storm',
  'as',
  'benchmark',
  'storm'],
 ['puerto',
  'rico',
  'was',
  'under',
  'hurricane',
  'watch',
  'saturday',
  'as',
  'the',
  'storm',
  'barreled',
  'towards',
  'the',
  'territory'],
 ['the',
  'world',
  'health',
  'organization',
  'is',
  'raising',
  'the',
  'alarm',
  'about',
  'second',
  'disaster',
  'in',
  'the',
  'wake',
  'of',
  'the',
  'deadly',
  'floods',
  'in',
  'pakistan',
  'this',
  'summer',
  'as',
  'doctors',
  'and',
  'medical',
  'workers',
  'on',
  'the',
  'ground',
  'race',
  'to',
  'battle',
  'outbreaks',
  'of',
  'waterborne',
  'and',
  'other',
  'diseases'],
 ['studies',
  'have',
  'repeatedly',
  'shown',
  'that',
  'ending',
  'public',
  'administration',
  'of',
  'water',
  'supplies',
  'doesn',
  'work',
  'but',
  'that',
  'now',
  'on',
  'the',
  'table',
  'in',
  'mississippi'],
 ['never',
  'in',
  'the',
  'history',
  'of',
  'the',
  'duesseldorf',
  'customs',
  'office',
  'has',
  'trail',
  'of',
  'slime',
  'led',
  'us',
  'to',
  'smuggled',
  'goods',
  'spokesman',
  'michael',
  'walk',
  'told',
  'the',
  'media'],
 ['the',
  'director',
  'of',
  'the',
  'original',
  'film',
  'joins',
  'writer',
  'of',
  'the',
  'sequel',
  'for',
  'the',
  'newest',
  'installment',
  'in',
  'the',
  'sci',
  'fi',
  'franchise'],
 ['republican',
  'outrage',
  'over',
  'the',
  'shoddy',
  'withdrawal',
  'from',
  'afghanistan',
  'hasn',
  'spurred',
  'support',
  'for',
  'resettling',
  'refugees'],
 ['sarah',
  'collins',
  'rudolph',
  'lost',
  'an',
  'eye',
  'and',
  'has',
  'pieces',
  'of',
  'glass',
  'inside',
  'her',
  'body',
  'from',
  'ku',
  'klux',
  'klan',
  'bombing',
  'that',
  'killed',
  'her',
  'sister',
  'and',
  'three',
  'other',
  'black',
  'girls',
  'inside',
  'an',
  'alabama',
  'church',
  'years',
  'ago'],
 ['boil',
  'water',
  'advisory',
  'has',
  'been',
  'lifted',
  'for',
  'mississippi',
  'capital',
  'and',
  'the',
  'state',
  'will',
  'stop',
  'handing',
  'out',
  'free',
  'bottled',
  'water',
  'on',
  'saturday'],
 ['the',
  'phantom',
  'of',
  'the',
  'opera',
  'broadway',
  'longest',
  'running',
  'show',
  'is',
  'scheduled',
  'to',
  'close',
  'in',
  'february',
  'victim',
  'of',
  'post',
  'pandemic',
  'softening',
  'in',
  'theater',
  'attendance',
  'in',
  'new',
  'york'],
 ['the',
  'former',
  'white',
  'house',
  'chief',
  'of',
  'staff',
  'has',
  'turned',
  'over',
  'records',
  'as',
  'part',
  'of',
  'federal',
  'investigation',
  'into',
  'the',
  'jan',
  'assault',
  'on',
  'the',
  'capitol'],
 ['the',
  'colombian',
  'american',
  'author',
  'new',
  'book',
  'lightlark',
  'was',
  'rejected',
  'numerous',
  'times',
  'until',
  'she',
  'went',
  'directly',
  'to',
  'her',
  'readers',
  'for',
  'support'],
 ['mykel',
  'gordon',
  'rushed',
  'to',
  'the',
  'woman',
  'aid',
  'and',
  'held',
  'down',
  'her',
  'assailant',
  'until',
  'police',
  'arrived',
  'remarkably',
  'this',
  'wasn',
  'the',
  'first',
  'time',
  'gordon',
  'may',
  'have',
  'saved',
  'life'],
 ['the',
  'oscar',
  'winner',
  'said',
  'she',
  'worked',
  'out',
  'for',
  'five',
  'hours',
  'day',
  'for',
  'her',
  'role',
  'in',
  'the',
  'new',
  'action',
  'movie'],
 ['the',
  'reality',
  'star',
  'told',
  'james',
  'corden',
  'she',
  'branching',
  'out',
  'because',
  'clearly',
  'it',
  'not',
  'working',
  'whatever',
  'doing'],
 ['the',
  'las',
  'vegas',
  'podcasters',
  'are',
  'hoping',
  'to',
  'find',
  'out',
  'who',
  'shot',
  'the',
  'rap',
  'icon',
  'years',
  'ago'],
 ['the',
  'grammy',
  'winning',
  'rapper',
  'surprised',
  'star',
  'struck',
  'children',
  'at',
  'the',
  'alexander',
  'macomb',
  'school',
  'in',
  'morris',
  'heights',
  'to',
  'make',
  'the',
  'announcement'],
 ['richardson',
  'the',
  'former',
  'ambassador',
  'to',
  'the',
  'united',
  'nations',
  'and',
  'frequent',
  'emissary',
  'in',
  'hostage',
  'negotiations',
  'held',
  'meetings',
  'with',
  'russian',
  'leaders'],
 ['the',
  'television',
  'awards',
  'ceremony',
  'lost',
  'roughly',
  'million',
  'viewers',
  'compared',
  'to',
  'its',
  'program'],
 ['white',
  'house',
  'press',
  'secretary',
  'karine',
  'jean',
  'pierre',
  'said',
  'rail',
  'shutdown',
  'is',
  'not',
  'acceptable',
  'and',
  'would',
  'harm',
  'families',
  'as',
  'well',
  'as',
  'businesses'],
 ['the',
  'state',
  'general',
  'treasurer',
  'is',
  'slated',
  'to',
  'face',
  'former',
  'cranston',
  'mayor',
  'allan',
  'fung',
  'in',
  'the',
  'general',
  'election'],
 ['firm',
  'that',
  'monitors',
  'false',
  'online',
  'claims',
  'reports',
  'that',
  'searches',
  'for',
  'information',
  'about',
  'prominent',
  'news',
  'topics',
  'on',
  'tiktok',
  'are',
  'likely',
  'to',
  'turn',
  'up',
  'results',
  'riddled',
  'with',
  'misinformation'],
 ['on',
  'monthly',
  'basis',
  'prices',
  'rose',
  'after',
  'flat',
  'reading',
  'in',
  'july'],
 ['the',
  'director',
  'was',
  'best',
  'known',
  'for',
  'the',
  'groundbreaking',
  'movie',
  'breathless'],
 ['they',
  're',
  'pressing',
  'for',
  'salary',
  'increases',
  'they',
  'say',
  'will',
  'help',
  'improve',
  'patient',
  'care',
  'by',
  'resolving',
  'understaffing',
  'stresses',
  'that',
  'have',
  'worsened',
  'in',
  'the',
  'pandemic'],
 ['cancer',
  'does',
  'not',
  'discriminate',
  'red',
  'and',
  'blue',
  'the',
  'president',
  'said',
  'monday',
  'beating',
  'cancer',
  'is',
  'something',
  'we',
  'can',
  'do',
  'together'],
 ['who',
  'we',
  'have',
  'on',
  'the',
  'field',
  'is',
  'who',
  'we',
  're',
  'gonna',
  'play',
  'scott',
  'told',
  'fox',
  'news',
  'sunday'],
 ['the',
  'race',
  'organizers',
  'say',
  'nonbinary',
  'athletes',
  'won',
  'have',
  'to',
  'register',
  'with',
  'the',
  'men',
  'or',
  'women',
  'divisions',
  'and',
  'provided',
  'qualifying',
  'times',
  'to',
  'guide',
  'their',
  'training'],
 ['varvaro',
  'pitched',
  'mostly',
  'with',
  'the',
  'atlanta',
  'braves',
  'and',
  'started',
  'his',
  'law',
  'enforcement',
  'career',
  'in'],
 ['democrats',
  'in',
  'the',
  'state',
  'more',
  'moderate',
  'house',
  'district',
  'are',
  'deciding',
  'who',
  'will',
  'take',
  'on',
  'popular',
  'republican',
  'former',
  'mayor'],
 ['biden',
  'plans',
  'to',
  'draw',
  'attention',
  'to',
  'new',
  'federally',
  'backed',
  'study',
  'that',
  'seeks',
  'to',
  'validate',
  'using',
  'blood',
  'tests',
  'to',
  'screen',
  'against',
  'multiple',
  'cancers'],
 ['the',
  'research',
  'based',
  'artist',
  'has',
  'found',
  'dynamic',
  'ways',
  'to',
  'confront',
  'conversations',
  'about',
  'female',
  'empowerment',
  'motherhood',
  'and',
  'labor',
  'in',
  'her',
  'artwork'],
 ['it',
  'not',
  'about',
  'or',
  'even',
  'tarnishing',
  'the',
  'reputation',
  'of',
  'sidney',
  'poitier',
  'rather',
  'the',
  'new',
  'documentary',
  'honors',
  'his',
  'humanity',
  'every',
  'facet',
  'of',
  'it'],
 ['carlos',
  'alcaraz',
  'defeated',
  'casper',
  'ruud',
  'in',
  'the',
  'open',
  'final',
  'to',
  'earn',
  'his',
  'first',
  'grand',
  'slam',
  'at',
  'age',
  'and',
  'become',
  'the',
  'youngest',
  'man',
  'to',
  'move',
  'up',
  'to',
  'no',
  'in',
  'the',
  'rankings'],
 ['firefighters',
  'made',
  'progress',
  'against',
  'huge',
  'northern',
  'california',
  'wildfire',
  'that',
  'was',
  'still',
  'growing',
  'and',
  'threatening',
  'thousands',
  'of',
  'mountain',
  'homes'],
 ['president',
  'joe',
  'biden',
  'has',
  'marked',
  'the',
  'st',
  'anniversary',
  'of',
  'the',
  'sept',
  'attacks',
  'taking',
  'part',
  'in',
  'somber',
  'wreath',
  'laying',
  'ceremony',
  'held',
  'at',
  'the',
  'pentagon',
  'under',
  'steady',
  'rain'],
 ['september',
  'th',
  'remains',
  'point',
  'for',
  'reflection',
  'on',
  'the',
  'attacks',
  'that',
  'reconfigured',
  'national',
  'security',
  'policy',
  'and',
  'spurred',
  'war',
  'on',
  'terror',
  'worldwide'],
 ['the',
  'plant',
  'one',
  'of',
  'the',
  'biggest',
  'atomic',
  'power',
  'stations',
  'in',
  'the',
  'world',
  'has',
  'been',
  'occupied',
  'by',
  'russian',
  'forces',
  'since',
  'early',
  'in',
  'the',
  'war',
  'which',
  'marked',
  'its',
  'th',
  'day',
  'on',
  'sunday'],
 ['visa',
  'adoption',
  'is',
  'significant',
  'as',
  'the',
  'largest',
  'payment',
  'network',
  'and',
  'will',
  'likely',
  'add',
  'pressure',
  'for',
  'mastercard',
  'and',
  'american',
  'express',
  'to',
  'adopt',
  'the',
  'code',
  'as',
  'well'],
 ['the',
  'justice',
  'department',
  'proposed',
  'two',
  'retired',
  'judges',
  'for',
  'the',
  'role',
  'trump',
  'team',
  'proposed',
  'retired',
  'judge',
  'and',
  'lawyer'],
 ['the',
  'director',
  'told',
  'the',
  'audience',
  'he',
  'was',
  'super',
  'excited',
  'to',
  'be',
  'finally',
  'finishing',
  'up',
  'movie',
  'two',
  'as',
  'he',
  'has',
  'three',
  'additional',
  'installments',
  'in',
  'the',
  'works'],
 ['russia',
  'defense',
  'ministry',
  'announced',
  'that',
  'troops',
  'will',
  'be',
  'pulled',
  'back',
  'in',
  'two',
  'area',
  'where',
  'ukrainian',
  'counter',
  'offensive',
  'has',
  'made',
  'significant',
  'advances'],
 ['after',
  'day',
  'heat',
  'wave',
  'that',
  'nearly',
  'overwhelmed',
  'the',
  'electrical',
  'grid',
  'southern',
  'california',
  'got',
  'cooler',
  'weather',
  'but',
  'also',
  'ferocious',
  'tropical',
  'storm'],
 ['ukrainian',
  'forces',
  'are',
  'claiming',
  'new',
  'success',
  'in',
  'their',
  'against',
  'russian',
  'forces',
  'in',
  'the',
  'east'],
 ['please',
  'join',
  'me',
  'in',
  'round',
  'of',
  'applause',
  'for',
  'years',
  'of',
  'service',
  'the',
  'pop',
  'star',
  'told',
  'the',
  'crowd',
  'after',
  'he',
  'paused',
  'his',
  'madison',
  'square',
  'garden',
  'performance'],
 ['derrell',
  'mcdavid',
  'testimony',
  'could',
  'be',
  'major',
  'blow',
  'to',
  'the',
  'singer',
  'hope',
  'of',
  'acquittal'],
 ['both',
  'british',
  'and',
  'international',
  'newspapers',
  'honor',
  'the',
  'passing',
  'of',
  'the',
  'longest',
  'reigning',
  'monarch'],
 ['the',
  'year',
  'old',
  'singer',
  'dancer',
  'and',
  'youtube',
  'icon',
  'will',
  'receive',
  'the',
  'gamechanger',
  'award',
  'for',
  'her',
  'focus',
  'on',
  'anti',
  'bullying',
  'efforts'],
 ['speaking',
  'from',
  'islamabad',
  'antonio',
  'guterres',
  'said',
  'countries',
  'bearing',
  'more',
  'responsibility',
  'for',
  'climate',
  'change',
  'should',
  'have',
  'faced',
  'this',
  'challenge'],
 ['clark',
  'county',
  'public',
  'administrator',
  'robert',
  'telles',
  'was',
  'arrested',
  'in',
  'the',
  'fatal',
  'stabbing',
  'of',
  'jeff',
  'german',
  'who',
  'had',
  'been',
  'investigating',
  'his',
  'office'],
 ['the',
  'internet',
  'ignited',
  'in',
  'approval',
  'over',
  'the',
  'former',
  'first',
  'lady',
  'hairstyle',
  'choice',
  'for',
  'the',
  'monumental',
  'day'],
 ['the',
  'actor',
  'said',
  'he',
  'was',
  'so',
  'badly',
  'concussed',
  'while',
  'shooting',
  'the',
  'series',
  'finale',
  'that',
  'he',
  'feared',
  'for',
  'his',
  'life',
  'and',
  'was',
  'holding',
  'onto',
  'the',
  'walls',
  'while',
  'recovering'],
 ['opponents',
  'of',
  'the',
  'measure',
  'claimed',
  'typos',
  'made',
  'the',
  'qualifying',
  'petitions',
  'but',
  'the',
  'state',
  'highest',
  'court',
  'rejected',
  'that',
  'argument'],
 ['the',
  'lawsuit',
  'says',
  'allowing',
  'homeless',
  'people',
  'tents',
  'to',
  'block',
  'city',
  'sidewalks',
  'makes',
  'it',
  'difficult',
  'for',
  'people',
  'using',
  'wheelchairs',
  'walkers',
  'or',
  'canes',
  'to',

In [16]:
max_len_output = max(len(sentence) for sentence in words1)
longest_sentence = max(words1, key=len)

print("Max number of words:", max_len_output)
print("Sentence with max words:", longest_sentence)

Max number of words: 41
Sentence with max words: ['when', 'elsa', 'avila', 'looks', 'at', 'the', 'scar', 'that', 'runs', 'down', 'her', 'torso', 'she', 'can', 'help', 'remember', 'may', 'when', 'gunman', 'stormed', 'her', 'fourth', 'grade', 'wing', 'at', 'robb', 'elementary', 'in', 'uvalde', 'texas', 'killing', 'children', 'and', 'two', 'teachers', 'and', 'leaving', 'her', 'and', 'others', 'wounded']

In [17]:
all_words1 = [word for sentence in words1 for word in sentence]

# Get unique words
unique_words_output = set(all_words1)

# Count them
print("Number of unique words:", len(unique_words_output))
print("Unique words:", unique_words_output)

Number of unique words: 5239

In [18]:
decoder_input=[one_hot(word, len(unique_words_output)) for word in decoder_input_data]
decoder_input

[[2289,
  1940,
  650,
  2254,
  2333,
  5142,
  2497,
  3472,
  477,
  1118,
  2578,
  3353,
  3761,
  78,
  255,
  976,
  1749,
  494,
  239,
  4240,
  4565,
  1749,
  1673,
  2296,
  1749,
  2164,
  3943,
  1568,
  4279,
  1749,
  2436],
 [2289,
  3160,
  1778,
  3664,
  4297,
  2033,
  4837,
  4926,
  1382,
  3160,
  1237,
  477,
  1749,
  1736,
  4565,
  1749,
  4228,
  3978,
  1749,
  466,
  324,
  477,
  1749,
  2164,
  3943,
  2734,
  3943,
  1076,
  4146,
  3291,
  3489],
 [2289,
  1280,
  1038,
  5063,
  2348,
  3749,
  1038,
  3655,
  36,
  5218,
  157,
  3803,
  5,
  2009],
 [2289,
  1067,
  2631,
  3403,
  255,
  297,
  1223,
  4771,
  3757,
  3943,
  4712,
  4837,
  3160,
  4127,
  2552,
  2971,
  1778,
  2690,
  602,
  4084,
  976,
  2348,
  1649,
  5046,
  2808,
  4146,
  513,
  1599],
 [2289,
  375,
  2632,
  1650,
  1759,
  673,
  1859,
  425,
  4565,
  2496,
  2933,
  4026,
  4837,
  3581,
  4026,
  2348,
  2371,
  3978,
  2503,
  4565,
  1749,
  179,
  1891,
  2803,
  3795,
  1883],
 [2289,
  1749,
  77,
  2541,
  752,
  1822,
  1778,
  3536,
  1703,
  4671,
  1749,
  1874,
  1649,
  1210,
  1223,
  3791,
  4304,
  1778,
  2140,
  4799,
  5143,
  3978,
  4026,
  2243,
  4065,
  4026,
  603,
  1486,
  2254],
 [2289,
  2753,
  3943,
  3050,
  3019,
  1038,
  944,
  2320,
  4279,
  1673,
  3715,
  3943,
  4158,
  4206,
  324,
  2056,
  2221,
  4932,
  4304,
  3984,
  255,
  944,
  466],
 [2289,
  4733,
  220,
  462,
  2348,
  239,
  3082,
  904,
  1379,
  1611,
  332,
  3148,
  1998,
  3978,
  1749,
  1657,
  4275,
  1749,
  2164,
  3943,
  4281],
 [2289,
  4146,
  2265,
  435,
  4183,
  3258,
  1869,
  1651,
  822,
  976,
  1749,
  3984,
  4565,
  1269,
  4837,
  4118,
  477,
  808,
  2348,
  4733,
  330,
  1511,
  5148],
 [2289,
  1937,
  3887,
  3702,
  2237,
  1749,
  487,
  4565,
  1749,
  161,
  3943,
  4883,
  477,
  1749,
  2164,
  2499,
  2879,
  2541,
  4036,
  5,
  2348,
  2731,
  5200,
  1469,
  4565,
  2044,
  4837,
  3235,
  476,
  4207],
 [2289,
  4901,
  4013,
  4033,
  3914,
  4021,
  45,
  334,
  1412,
  3266,
  3811,
  2753,
  2627,
  477,
  4135,
  2348,
  1420,
  3093,
  1016,
  150,
  2221,
  4671,
  1749,
  745,
  2861],
 [2289,
  1749,
  2345,
  4110,
  2348,
  3771,
  738,
  4565,
  580,
  150,
  1749,
  1599,
  4279,
  2837,
  151,
  2753,
  1778,
  4695,
  4565,
  1749,
  5132,
  4042,
  4377,
  4146,
  324,
  3493,
  4643],
 [2289,
  3478,
  4993,
  4275,
  1749,
  2610,
  4837,
  4216,
  1771,
  4837,
  1778,
  1083,
  477,
  48,
  2115,
  438,
  4162,
  2879,
  3338],
 [2289,
  4695,
  410,
  3943,
  4367,
  3050,
  3160,
  4756,
  3082,
  1223,
  1749,
  2380,
  3352,
  334,
  2859,
  3176,
  477,
  389,
  2348,
  94,
  2856],
 [2289,
  3886,
  3911,
  4163,
  781,
  1749,
  518,
  4565,
  3254,
  2333,
  4753,
  2933,
  781,
  4013,
  56,
  477,
  4138,
  4146,
  2348,
  3048,
  466,
  976,
  1749,
  3887,
  1801,
  3477,
  1749,
  1500,
  232,
  1918],
 [2289,
  3591,
  3943,
  2460,
  829,
  1338,
  477,
  4244,
  979,
  2387,
  886,
  1657,
  1669,
  3373,
  1236,
  276,
  4837,
  804,
  2461,
  3911,
  239,
  4106],
 [2289,
  3905,
  483,
  4679,
  3646,
  3910,
  665,
  4837,
  1691,
  4951,
  1749,
  3751,
  936,
  4363,
  1749,
  1179,
  4565,
  2348,
  4579,
  3472,
  2848,
  4156],
 [2289,
  5005,
  93,
  2753,
  1992,
  1749,
  3291,
  3489,
  526,
  4886,
  3148,
  745,
  4950,
  2729,
  976,
  602,
  1257,
  1847,
  2482,
  4013,
  287],
 [2289,
  1749,
  3073,
  4837,
  4984,
  306,
  2531,
  1489,
  477,
  1505,
  255,
  5118,
  4394,
  3803,
  337,
  1749,
  212,
  4279,
  5212,
  477,
  5151,
  1749,
  4207],
 [2289,
  1749,
  2610,
  4837,
  4216,
  1771,
  5060,
  5023,
  2348,
  4452,
  4932,
  1749,
  3353,
  1657,
  1816,
  4324,
  3823,
  4070,
  4375,
  1749,
  1859,
  2980,
  4837,
  503,
  1261],
 [2289,
  4279,
  1749,
  2115,
  4552,
  4497,
  3542,
  4013,
  3282,
  3844,
  1749,
  1822,
  3978,
  2462,
  3050,
  1749,
  1291,
  3943,
  4920,
  1958,
  4565,
  3241,
  4921,
  2062,
  4163,
  3954,
  4532,
  1958],
 [2289, 161, 4763, 3506, 4932, 4825, 976, 2142, 16],
 [2289,
  1749,
  1657,
  407,
  3949,
  1749,
  3840,
  629,
  4837,
  2975,
  3070,
  4837,
  273,
  4146,
  503,
  1261,
  2321,
  1749,
  4063,
  2254,
  1749,
  4407,
  1778,
  2530],
 [2289,
  1749,
  2368,
  2254,
  1463,
  1778,
  2800,
  4146,
  1749,
  3044,
  1153,
  2963,
  4893,
  1223,
  3453,
  1382,
  2333,
  4834,
  1422,
  2348,
  4552,
  1782,
  1749,
  976,
  3702,
  2254],
 [2289,
  944,
  2713,
  1634,
  1010,
  1223,
  2348,
  868,
  2288,
  4932,
  2044,
  3943,
  3996,
  3850,
  1422,
  3495,
  1196],
 [2289,
  5023,
  2119,
  2348,
  463,
  2218,
  4837,
  1324,
  4083,
  1778,
  4982,
  4146,
  105,
  4146,
  3236,
  3395],
 [2289, 4545, 496, 2379, 4098, 2348, 4335, 3798, 3660, 1280, 3453],
 [2289,
  161,
  3485,
  657,
  4837,
  1136,
  1593,
  463,
  657,
  3614,
  1430,
  1249,
  4565,
  2956,
  45,
  4432,
  4837,
  791,
  477,
  4411,
  4837,
  745,
  4377,
  477,
  3825,
  3450,
  2723],
 [2289,
  1749,
  1635,
  435,
  2254,
  1341,
  4565,
  602,
  2277,
  193,
  3681,
  9,
  2143,
  976,
  2986,
  3050,
  3943,
  3949,
  26,
  2109,
  1998],
 [2289,
  3710,
  241,
  1724,
  4932,
  1749,
  3828,
  1566,
  410,
  4013,
  4061,
  1749,
  722,
  1615,
  4837,
  1749,
  2637,
  3782,
  725],
 [2289,
  2164,
  3943,
  161,
  3485,
  657,
  4146,
  3231,
  4279,
  1749,
  1599,
  4565,
  2449,
  1879,
  797,
  934,
  602,
  829,
  3795,
  3949,
  477,
  1749,
  3660,
  2243,
  2743,
  1749,
  2449,
  3943,
  1286,
  2240,
  2348,
  4044,
  3199],
 [2289,
  2283,
  1876,
  1856,
  2425,
  3450,
  991,
  1386,
  36,
  5199,
  2260,
  4837,
  4146,
  5013,
  4557,
  1749,
  690,
  191,
  2091,
  488,
  1749,
  1076,
  4565,
  4601,
  4193,
  4065],
 [2289,
  1223,
  5143,
  1749,
  745,
  3943,
  1136,
  337,
  257,
  4565,
  2562,
  4731,
  4203,
  2570,
  4837,
  1005,
  949],
 [2289,
  1749,
  2557,
  2541,
  752,
  3052,
  1237,
  1422,
  1749,
  4666,
  4146,
  2348,
  691,
  4393,
  477,
  2994,
  316],
 [2289,
  4146,
  2813,
  3908,
  3082,
  4036,
  5,
  3909,
  477,
  1749,
  4352,
  1446,
  1657,
  4932,
  2348,
  3527,
  1657],
 [2289,
  503,
  1261,
  1778,
  3914,
  2348,
  3478,
  3345,
  1517,
  4932,
  1749,
  1657,
  2879,
  1261,
  1749,
  2164,
  3943,
  4281],
 [2289,
  1749,
  745,
  1940,
  4424,
  5142,
  3007,
  1749,
  3616,
  818,
  2348,
  239,
  55,
  4146,
  1749,
  4412,
  4565,
  1749,
  957,
  3070,
  4146,
  3332,
  2879,
  3283,
  4932,
  2564,
  4837,
  3146,
  2,
  1223,
  1749,
  4529,
  678,
  477,
  2053,
  127,
  4565,
  2213,
  4837,
  1966,
  3813],
 [2289,
  5034,
  5063,
  3665,
  4927,
  3050,
  4217,
  337,
  4110,
  4565,
  1611,
  854,
  1158,
  36,
  991,
  3865,
  3050,
  3943,
  3585,
  1223,
  1749,
  851,
  4146,
  5189],
 [2289,
  2379,
  4146,
  1749,
  634,
  4565,
  1749,
  2138,
  2327,
  1076,
  4013,
  2348,
  562,
  4565,
  544,
  2470,
  2922,
  477,
  979,
  2540,
  1245,
  4679,
  2032,
  5164,
  1749,
  950],
 [2289,
  1749,
  435,
  4565,
  1749,
  3355,
  2509,
  450,
  2812,
  2348,
  1679,
  4565,
  1749,
  1450,
  2670,
  4279,
  1749,
  261,
  1226,
  4146,
  1749,
  1832,
  1448,
  245],
 [2289,
  4936,
  2160,
  4375,
  1749,
  4366,
  2164,
  3943,
  1115,
  45,
  105,
  371,
  36,
  5233,
  4135,
  4279,
  581,
  248],
 [2289,
  2520,
  2497,
  2075,
  3178,
  944,
  3357,
  4837,
  4013,
  3698,
  4565,
  345,
  2411,
  4026,
  4883,
  45,
  2348,
  4906,
  3235,
  3731,
  5012,
  3050,
  4308,
  4026,
  3252,
  4837,
  3148,
  1966,
  4532,
  2791,
  2411,
  944,
  4965,
  1495,
  1330,
  3908,
  4577],
 [2289,
  2348,
  3252,
  1611,
  4878,
  4013,
  2337,
  1875,
  4279,
  5189,
  3943,
  4169,
  4837,
  1749,
  3782,
  4036,
  4153,
  225,
  3949,
  4332,
  74,
  1611,
  1223,
  1517],
 [2289,
  1749,
  4775,
  4565,
  1749,
  5191,
  339,
  3943,
  5019,
  1522,
  936,
  5142,
  1231,
  477,
  2240,
  4146,
  3362,
  545,
  2348,
  962,
  4565,
  1504,
  610,
  4986,
  4146,
  1606,
  3285,
  4146,
  1673,
  3715],
 [2289,
  1749,
  822,
  1937,
  3887,
  1721,
  4565,
  2749,
  4013,
  3433,
  4375,
  2606,
  4932,
  702,
  4565,
  2348,
  3286,
  2190,
  1422,
  1749,
  1500,
  232,
  3670,
  464,
  1223,
  1749,
  2000],
 [2289,
  1749,
  4811,
  4921,
  5220,
  3943,
  1673,
  619,
  2479,
  1778,
  3320,
  442,
  276,
  1280,
  4304,
  3795,
  3702,
  477,
  4026,
  849,
  4279,
  4135],
 [2289,
  2175,
  4874,
  4034,
  477,
  1749,
  1822,
  3943,
  286,
  4837,
  275,
  3587,
  4026,
  2468,
  1280,
  316,
  1424,
  5164,
  2879,
  1386,
  36,
  1749,
  1136,
  3159,
  4874,
  2559,
  5063,
  1590,
  2348,
  2026],
 [2289,
  1749,
  3261,
  1108,
  2254,
  4304,
  5007,
  3949,
  4279,
  2266,
  5110,
  2348,
  3495,
  4279,
  4026,
  3871,
  4146,
  1749,
  1673,
  2511,
  193],
 [2289,
  1749,
  4396,
  311,
  5164,
  3254,
  585,
  4304,
  3943,
  2949,
  3949,
  886,
  868,
  2333,
  3943,
  3086,
  1703,
  3109,
  2971,
  2756,
  3109],
 [2289,
  1749,
  4545,
  496,
  992,
  3681,
  4894,
  477,
  4228,
  3949,
  2753,
  1088,
  1749,
  2968,
  784,
  1834,
  3908,
  4577],
 [2289,
  1749,
  979,
  4633,
  4542,
  784,
  311,
  3240,
  2533,
  4671,
  1749,
  4876,
  4137,
  2503,
  4146,
  4850,
  4742,
  477,
  3698,
  1749,
  2889],
 [2289,
  844,
  1749,
  822,
  2164,
  3943,
  921,
  477,
  1749,
  4262,
  1704,
  4837,
  2348,
  3677,
  4361,
  4146,
  607,
  138,
  275,
  1575,
  976,
  2776,
  4377],
 [2289,
  1749,
  141,
  2859,
  4405,
  3178,
  335,
  589,
  2217,
  239,
  2034,
  1051,
  477,
  3235,
  3670,
  2971],
 [2289,
  1937,
  3887,
  3860,
  2308,
  1575,
  4884,
  1408,
  2254,
  2348,
  836,
  255,
  5142,
  3086,
  3541,
  4837,
  3761,
  3398,
  2155,
  4932,
  498,
  4932,
  2088],
 [2289,
  1749,
  3782,
  3943,
  4193,
  3401,
  5142,
  1650,
  477,
  3553,
  822,
  4380,
  4630,
  2262,
  2148,
  1513,
  4146,
  1749,
  4193,
  757],
 [2289,
  2348,
  2164,
  3943,
  673,
  3050,
  1590,
  1856,
  1808,
  4367,
  2462,
  3050,
  3425,
  4279,
  2425,
  818,
  3898,
  3956,
  5027,
  1223,
  3260,
  3681,
  1769,
  477,
  3029,
  255,
  4443,
  3121,
  976,
  1851],
 [2289,
  1223,
  2348,
  4036,
  2909,
  2670,
  3153,
  3612,
  589,
  3978,
  2348,
  4406,
  4256,
  4146,
  3612],
 [2289, 1749, 435, 1778, 2258, 1724, 4279, 1749, 1453, 193, 2797],
 [2289,
  1538,
  720,
  106,
  4279,
  1767,
  2270,
  1538,
  2237,
  4036,
  4699,
  1541,
  5137,
  1976,
  4297,
  3178,
  1467,
  4770,
  3050,
  5063,
  1580,
  4146,
  1749,
  610],
 [2289,
  2532,
  2943,
  3086,
  2449,
  2006,
  4837,
  1547,
  1749,
  161,
  2254,
  5143,
  3810,
  2532,
  5142,
  4433,
  728,
  2631,
  4066,
  4394],
 [2289,
  2753,
  728,
  5063,
  1223,
  1749,
  4552,
  5142,
  2753,
  728,
  720,
  3729,
  4211,
  614,
  5164,
  3528,
  3956,
  3453],
 [2289,
  1749,
  678,
  3943,
  4190,
  2237,
  1484,
  5058,
  13,
  36,
  5063,
  477,
  5040,
  976,
  1749,
  3880,
  3943,
  395,
  1221,
  3943,
  3252,
  4837,
  4230,
  1412,
  276,
  477,
  171,
  3450,
  249],
 [2289,
  18,
  1596,
  4917,
  976,
  1749,
  4903,
  4170,
  4837,
  3253,
  602,
  2768,
  3863,
  576,
  4146,
  3880],
 [2289,
  2381,
  4146,
  1749,
  3782,
  3943,
  4733,
  1849,
  3887,
  3938,
  3681,
  2534,
  2753,
  4036,
  1989,
  1223,
  2348,
  2859,
  4936,
  822,
  4630],
 [2289,
  657,
  4652,
  477,
  4247,
  1681,
  477,
  2348,
  1673,
  3546,
  2531,
  365,
  3050,
  5096,
  477,
  17,
  668,
  1983,
  3747,
  477,
  1697,
  150,
  4063,
  2304],
 [2289,
  1749,
  794,
  5198,
  1627,
  4013,
  2140,
  4657,
  2272,
  477,
  502,
  2963,
  818,
  3512,
  2807,
  3460,
  4837,
  3219,
  4146,
  4026,
  1343],
 [2289,
  2333,
  3943,
  3086,
  818,
  5208,
  395,
  3066,
  3339,
  1749,
  1433,
  4565,
  3149,
  3327,
  581,
  1749,
  1673,
  3445,
  3859,
  602,
  1023,
  4123,
  4025,
  4565,
  2333],
 [2289,
  1318,
  3736,
  1352,
  4478,
  2537,
  4146,
  1749,
  2164,
  3943,
  351,
  786,
  477,
  3136,
  602,
  1136,
  1994,
  4805,
  4671,
  2601,
  2557,
  4837,
  532,
  1749,
  2097,
  410,
  477,
  1811,
  255,
  477,
  3954,
  589,
  4146,
  1749,
  2898],
 [2289,
  280,
  1141,
  2122,
  150,
  2348,
  1132,
  2473,
  1715,
  4620,
  3050,
  1778,
  9,
  3771,
  4837,
  420,
  1249,
  4565,
  2269,
  4673],
 [2289,
  161,
  3485,
  657,
  4013,
  4242,
  1749,
  2478,
  4615,
  4565,
  1749,
  4487,
  226,
  1641,
  1957,
  702,
  4146,
  2348,
  3935,
  3622,
  2743,
  4405,
  275,
  4671,
  1749,
  2670,
  3914,
  2348,
  722,
  4070],
 [2289,
  4352,
  1000,
  2029,
  2348,
  766,
  4279,
  2791,
  1223,
  1749,
  2594,
  1641,
  3050,
  2096,
  3044,
  4206,
  1621,
  4837,
  5233,
  2348,
  2164,
  3943,
  4207,
  1223,
  189,
  736],
 [2289,
  1749,
  3244,
  4695,
  4565,
  1749,
  2813,
  2289,
  4611,
  3840,
  1132,
  4146,
  1749,
  745,
  4013,
  2337,
  4338,
  4297,
  2776,
  4121,
  2887,
  3472,
  4146,
  1749,
  4207,
  2210,
  4242,
  3235,
  3262,
  3495,
  1223,
  3453],
 [2289,
  3236,
  3943,
  2457,
  5142,
  1016,
  4932,
  1749,
  2080,
  659,
  3070,
  4837,
  4036,
  1769,
  1943,
  4021,
  4279,
  1174,
  4837,
  4921,
  3474,
  477,
  5121,
  1749,
  3343,
  4932,
  498],
 [2289,
  1749,
  4753,
  566,
  1433,
  1296,
  3330,
  3670,
  4279,
  1749,
  3871,
  971,
  3943,
  807,
  1433,
  2348,
  3330,
  2810,
  4837,
  2348,
  5222],
 [2289,
  1749,
  435,
  5164,
  1749,
  4395,
  3160,
  1778,
  3746,
  252,
  477,
  5,
  3717,
  4637,
  255,
  193,
  1296,
  4932,
  3160,
  4013,
  3148,
  5156,
  695,
  4146,
  1749,
  366],
 [2289,
  2044,
  3943,
  3632,
  229,
  4738,
  3050,
  4651,
  4036,
  5,
  3160,
  1736,
  4146,
  1296,
  2454,
  2321,
  2348,
  3725,
  1843,
  3554,
  4013,
  1141,
  1016,
  715],
 [2289,
  3978,
  2348,
  2813,
  3495,
  5017,
  738,
  3050,
  2461,
  2121,
  1749,
  11,
  629,
  2589,
  1715,
  3700,
  2460,
  546,
  3865,
  4081,
  2348,
  3626,
  3558,
  1657],
 [2289,
  3725,
  4121,
  3681,
  2898,
  1673,
  5001,
  4146,
  3450,
  1069,
  150,
  2776,
  4121,
  4146,
  1749,
  2650],
 [2289,
  5220,
  3593,
  2628,
  4146,
  2348,
  1923,
  4565,
  3233,
  4279,
  5039,
  3908,
  4565,
  332,
  1749,
  3262,
  311,
  5164,
  1749,
  246,
  3978,
  3160,
  19,
  602,
  960,
  1521,
  278,
  4060],
 [2289,
  1328,
  4591,
  3943,
  1633,
  3803,
  5,
  2348,
  2463,
  3263,
  477,
  1749,
  1513,
  2057,
  308,
  3943,
  2442,
  4565,
  2773],
 [2289,
  4418,
  3356,
  4837,
  3815,
  326,
  5039,
  1749,
  2458,
  4565,
  1749,
  2164,
  4968,
  3943,
  5019,
  477,
  3036],
 [2289,
  1749,
  2557,
  2541,
  752,
  308,
  3841,
  4837,
  667,
  784,
  4036,
  2707,
  1749,
  1446,
  5004,
  4992,
  4279,
  4026,
  154,
  1223,
  432,
  2930,
  1489],
 [2289,
  2954,
  45,
  2505,
  831,
  4576,
  2254,
  600,
  4237,
  4733,
  788,
  4279,
  4528,
  535,
  1414,
  5063,
  2528,
  2879,
  4311],
 [2289,
  3524,
  35,
  337,
  3476,
  241,
  990,
  1778,
  431,
  4146,
  1749,
  4231,
  481,
  4565,
  3549,
  4159,
  2753,
  4098,
  2337,
  3477,
  602,
  1076],
 [2289,
  1749,
  508,
  1839,
  4146,
  2703,
  4375,
  1749,
  822,
  1136,
  1593,
  3943,
  1647,
  2119,
  4279,
  1749,
  5144,
  3495],
 [2289,
  1749,
  3359,
  2254,
  3160,
  1778,
  481,
  2634,
  3587,
  677,
  3674,
  1749,
  4950,
  1268,
  3050,
  3160,
  461,
  4279,
  602,
  2026,
  4837,
  1778,
  3820,
  37,
  1749,
  264,
  677,
  4790],
 [2289,
  3344,
  4565,
  1749,
  261,
  4977,
  1545,
  1141,
  1749,
  1412,
  5044,
  4840,
  3865,
  1749,
  3782,
  3943,
  2065,
  2333,
  3320,
  3050,
  1502],
 [2289,
  1749,
  167,
  934,
  1837,
  4515,
  3082,
  3943,
  4022,
  477,
  2775,
  420,
  4052,
  1088,
  2333,
  4964,
  4279,
  3082,
  668,
  1847,
  394,
  395,
  849,
  477,
  3951,
  3950],
 [2289,
  1749,
  3407,
  4146,
  3100,
  944,
  420,
  85,
  4037,
  1383,
  4837,
  4303,
  4418,
  2,
  4837,
  3453,
  2411,
  1749,
  2030,
  5148,
  3432],
 [2289,
  1749,
  1748,
  4841,
  185,
  4036,
  3717,
  5,
  2348,
  4301,
  4565,
  1749,
  1499,
  887,
  4512,
  976,
  3735,
  1966,
  1401,
  3110,
  5007],
 [2289,
  4146,
  5132,
  4565,
  1749,
  44,
  3734,
  809,
  3050,
  3655,
  4717,
  2370,
  5125,
  3614,
  4296,
  4935,
  3602,
  395,
  1357,
  1334,
  1538,
  1805,
  4671,
  4573],
 [2289,
  3289,
  3681,
  5004,
  1736,
  4837,
  614,
  5142,
  449,
  477,
  3284,
  4146,
  3066,
  3978,
  1749,
  610,
  5171,
  1749,
  2956,
  1521,
  3943,
  849],
 [2289,
  62,
  3702,
  4146,
  3113,
  4069,
  2237,
  944,
  3472,
  90,
  3840,
  2253,
  5142,
  1071,
  803,
  3631,
  3066,
  4932,
  506,
  4013,
  2337,
  2128],
 [2289,
  1749,
  2542,
  4565,
  1749,
  3815,
  4611,
  3212,
  3334,
  206,
  1749,
  2164,
  2499,
  4206,
  3086,
  3050,
  4433,
  239,
  239,
  2530,
  3803,
  1989,
  3575,
  4671,
  4185],
 [2289,
  2055,
  1641,
  5063,
  532,
  2348,
  3771,
  590,
  477,
  2164,
  3943,
  2521,
  976,
  334,
  980,
  3514,
  696,
  4065,
  2887,
  3928,
  2541],
 [2289, 2348, 239, 3407, 4308, 1296, 3082, 4146, 2473, 1715, 2879, 4758],
 [2289,
  1749,
  2989,
  4213,
  2824,
  1594,
  3383,
  3700,
  2877,
  1422,
  117,
  31,
  2792,
  4146,
  2348,
  2813,
  3612,
  1421,
  477,
  1749,
  4956],
 [2289,
  1749,
  420,
  2029,
  3914,
  2348,
  3252,
  1611,
  4926,
  2210,
  1136,
  3795,
  1422,
  4451,
  1223,
  3612,
  1917],
 [2289,
  1749,
  3100,
  950,
  4044,
  1778,
  491,
  4279,
  3034,
  4565,
  3864,
  3271,
  4942,
  4984,
  477,
  2425,
  818,
  2533,
  1223,
  5236],
 [2289,
  26,
  5142,
  1673,
  980,
  2347,
  1928,
  1749,
  4069,
  305,
  3943,
  337,
  2521,
  3050,
  9,
  4099,
  36,
  3984,
  4837,
  2348,
  5047,
  316,
  1532,
  3050,
  366,
  2155,
  3655,
  36,
  5172],
 [2289,
  1749,
  910,
  3088,
  3978,
  1749,
  657,
  4110,
  2272,
  3050,
  1749,
  2776,
  2012,
  4146,
  4615,
  1010,
  2391,
  4565,
  1045,
  2103,
  737,
  4279,
  3951,
  4146,
  4257],
 [2289,
  1749,
  4932,
  2333,
  1778,
  308,
  2254,
  3160,
  4081,
  1158,
  36,
  1091,
  366,
  5198,
  3961,
  1651,
  4837,
  2742],
 [2289,
  4416,
  4441,
  2254,
  1851,
  3545,
  1749,
  4165,
  4279,
  5156,
  2238,
  4192,
  4837,
  3066,
  76,
  1223,
  757,
  3495],
 [2289, 139, 279, 4359, 4903, 4098, 182, 982, 2741, 477, 2775, 1749, 1429],
 [2289,
  3160,
  3943,
  2903,
  4146,
  4771,
  1294,
  4932,
  2236,
  4932,
  3160,
  1158,
  36,
  2773,
  2628,
  395,
  4771,
  2243,
  1749,
  4975,
  5054],
 [2289,
  1382,
  679,
  2435,
  4112,
  4671,
  1749,
  3903,
  3050,
  370,
  3587,
  4026,
  3041,
  4304,
  2631,
  36,
  4699,
  2440,
  2559,
  5113,
  1382,
  2348,
  1381,
  2928,
  4026,
  4068,
  4430,
  2106,
  4671,
  2032,
  488,
  4146,
  2656,
  4069,
  1782,
  2557,
  2533,
  4837,
  1296,
  172,
  4837,
  3068,
  4026,
  4837,
  4588,
  2493],
 [2289,
  1468,
  3806,
  2741,
  1223,
  4058,
  477,
  3178,
  3978,
  950,
  2336,
  1152,
  4657,
  956,
  5148,
  2644,
  4336,
  3943,
  2774,
  477,
  432,
  2866,
  2582],
 [2289,
  316,
  4146,
  4393,
  2237,
  944,
  1786,
  4013,
  2337,
  1141,
  4146,
  1749,
  4246,
  4565,
  2348,
  1822,
  2753,
  1778,
  1707,
  677,
  3556],
 [2289,
  3651,
  4565,
  5189,
  3943,
  1341,
  4532,
  4169,
  9,
  3655,
  36,
  5063,
  5229,
  1611,
  3978,
  5203,
  1580,
  1749,
  366,
  4757],
 [2289,
  1486,
  1097,
  3050,
  4733,
  3232,
  5142,
  1782,
  4932,
  3145,
  3201,
  2211,
  45,
  663,
  9,
  5203,
  3050,
  5063,
  4308,
  2461,
  589,
  208,
  3082],
 [2289,
  1444,
  2753,
  4751,
  1749,
  2559,
  5113,
  3674,
  4671,
  2032,
  488,
  4146,
  4069,
  3681,
  2495,
  1749,
  3283,
  976,
  2348,
  4260,
  4565,
  2911,
  1940,
  4763,
  4362,
  3030],
 [2289,
  280,
  4837,
  5047,
  4070,
  196,
  1547,
  4565,
  1387,
  1239,
  1223,
  3453,
  1127,
  534,
  3232,
  4837,
  2595,
  980,

In [19]:
decoder_target=[one_hot(word, len(unique_words_output)) for word in decoder_target_data]
decoder_target

[[1940,
  650,
  2254,
  2333,
  5142,
  2497,
  3472,
  477,
  1118,
  2578,
  3353,
  3761,
  78,
  255,
  976,
  1749,
  494,
  239,
  4240,
  4565,
  1749,
  1673,
  2296,
  1749,
  2164,
  3943,
  1568,
  4279,
  1749,
  2436,
  2628],
 [3160,
  1778,
  3664,
  4297,
  2033,
  4837,
  4926,
  1382,
  3160,
  1237,
  477,
  1749,
  1736,
  4565,
  1749,
  4228,
  3978,
  1749,
  466,
  324,
  477,
  1749,
  2164,
  3943,
  2734,
  3943,
  1076,
  4146,
  3291,
  3489,
  2628],
 [1280,
  1038,
  5063,
  2348,
  3749,
  1038,
  3655,
  36,
  5218,
  157,
  3803,
  5,
  2009,
  2628],
 [1067,
  2631,
  3403,
  255,
  297,
  1223,
  4771,
  3757,
  3943,
  4712,
  4837,
  3160,
  4127,
  2552,
  2971,
  1778,
  2690,
  602,
  4084,
  976,
  2348,
  1649,
  5046,
  2808,
  4146,
  513,
  1599,
  2628],
 [375,
  2632,
  1650,
  1759,
  673,
  1859,
  425,
  4565,
  2496,
  2933,
  4026,
  4837,
  3581,
  4026,
  2348,
  2371,
  3978,
  2503,
  4565,
  1749,
  179,
  1891,
  2803,
  3795,
  1883,
  2628],
 [1749,
  77,
  2541,
  752,
  1822,
  1778,
  3536,
  1703,
  4671,
  1749,
  1874,
  1649,
  1210,
  1223,
  3791,
  4304,
  1778,
  2140,
  4799,
  5143,
  3978,
  4026,
  2243,
  4065,
  4026,
  603,
  1486,
  2254,
  2628],
 [2753,
  3943,
  3050,
  3019,
  1038,
  944,
  2320,
  4279,
  1673,
  3715,
  3943,
  4158,
  4206,
  324,
  2056,
  2221,
  4932,
  4304,
  3984,
  255,
  944,
  466,
  2628],
 [4733,
  220,
  462,
  2348,
  239,
  3082,
  904,
  1379,
  1611,
  332,
  3148,
  1998,
  3978,
  1749,
  1657,
  4275,
  1749,
  2164,
  3943,
  4281,
  2628],
 [4146,
  2265,
  435,
  4183,
  3258,
  1869,
  1651,
  822,
  976,
  1749,
  3984,
  4565,
  1269,
  4837,
  4118,
  477,
  808,
  2348,
  4733,
  330,
  1511,
  5148,
  2628],
 [1937,
  3887,
  3702,
  2237,
  1749,
  487,
  4565,
  1749,
  161,
  3943,
  4883,
  477,
  1749,
  2164,
  2499,
  2879,
  2541,
  4036,
  5,
  2348,
  2731,
  5200,
  1469,
  4565,
  2044,
  4837,
  3235,
  476,
  4207,
  2628],
 [4901,
  4013,
  4033,
  3914,
  4021,
  45,
  334,
  1412,
  3266,
  3811,
  2753,
  2627,
  477,
  4135,
  2348,
  1420,
  3093,
  1016,
  150,
  2221,
  4671,
  1749,
  745,
  2861,
  2628],
 [1749,
  2345,
  4110,
  2348,
  3771,
  738,
  4565,
  580,
  150,
  1749,
  1599,
  4279,
  2837,
  151,
  2753,
  1778,
  4695,
  4565,
  1749,
  5132,
  4042,
  4377,
  4146,
  324,
  3493,
  4643,
  2628],
 [3478,
  4993,
  4275,
  1749,
  2610,
  4837,
  4216,
  1771,
  4837,
  1778,
  1083,
  477,
  48,
  2115,
  438,
  4162,
  2879,
  3338,
  2628],
 [4695,
  410,
  3943,
  4367,
  3050,
  3160,
  4756,
  3082,
  1223,
  1749,
  2380,
  3352,
  334,
  2859,
  3176,
  477,
  389,
  2348,
  94,
  2856,
  2628],
 [3886,
  3911,
  4163,
  781,
  1749,
  518,
  4565,
  3254,
  2333,
  4753,
  2933,
  781,
  4013,
  56,
  477,
  4138,
  4146,
  2348,
  3048,
  466,
  976,
  1749,
  3887,
  1801,
  3477,
  1749,
  1500,
  232,
  1918,
  2628],
 [3591,
  3943,
  2460,
  829,
  1338,
  477,
  4244,
  979,
  2387,
  886,
  1657,
  1669,
  3373,
  1236,
  276,
  4837,
  804,
  2461,
  3911,
  239,
  4106,
  2628],
 [3905,
  483,
  4679,
  3646,
  3910,
  665,
  4837,
  1691,
  4951,
  1749,
  3751,
  936,
  4363,
  1749,
  1179,
  4565,
  2348,
  4579,
  3472,
  2848,
  4156,
  2628],
 [5005,
  93,
  2753,
  1992,
  1749,
  3291,
  3489,
  526,
  4886,
  3148,
  745,
  4950,
  2729,
  976,
  602,
  1257,
  1847,
  2482,
  4013,
  287,
  2628],
 [1749,
  3073,
  4837,
  4984,
  306,
  2531,
  1489,
  477,
  1505,
  255,
  5118,
  4394,
  3803,
  337,
  1749,
  212,
  4279,
  5212,
  477,
  5151,
  1749,
  4207,
  2628],
 [1749,
  2610,
  4837,
  4216,
  1771,
  5060,
  5023,
  2348,
  4452,
  4932,
  1749,
  3353,
  1657,
  1816,
  4324,
  3823,
  4070,
  4375,
  1749,
  1859,
  2980,
  4837,
  503,
  1261,
  2628],
 [4279,
  1749,
  2115,
  4552,
  4497,
  3542,
  4013,
  3282,
  3844,
  1749,
  1822,
  3978,
  2462,
  3050,
  1749,
  1291,
  3943,
  4920,
  1958,
  4565,
  3241,
  4921,
  2062,
  4163,
  3954,
  4532,
  1958,
  2628],
 [161, 4763, 3506, 4932, 4825, 976, 2142, 16, 2628],
 [1749,
  1657,
  407,
  3949,
  1749,
  3840,
  629,
  4837,
  2975,
  3070,
  4837,
  273,
  4146,
  503,
  1261,
  2321,
  1749,
  4063,
  2254,
  1749,
  4407,
  1778,
  2530,
  2628],
 [1749,
  2368,
  2254,
  1463,
  1778,
  2800,
  4146,
  1749,
  3044,
  1153,
  2963,
  4893,
  1223,
  3453,
  1382,
  2333,
  4834,
  1422,
  2348,
  4552,
  1782,
  1749,
  976,
  3702,
  2254,
  2628],
 [944,
  2713,
  1634,
  1010,
  1223,
  2348,
  868,
  2288,
  4932,
  2044,
  3943,
  3996,
  3850,
  1422,
  3495,
  1196,
  2628],
 [5023,
  2119,
  2348,
  463,
  2218,
  4837,
  1324,
  4083,
  1778,
  4982,
  4146,
  105,
  4146,
  3236,
  3395,
  2628],
 [4545, 496, 2379, 4098, 2348, 4335, 3798, 3660, 1280, 3453, 2628],
 [161,
  3485,
  657,
  4837,
  1136,
  1593,
  463,
  657,
  3614,
  1430,
  1249,
  4565,
  2956,
  45,
  4432,
  4837,
  791,
  477,
  4411,
  4837,
  745,
  4377,
  477,
  3825,
  3450,
  2723,
  2628],
 [1749,
  1635,
  435,
  2254,
  1341,
  4565,
  602,
  2277,
  193,
  3681,
  9,
  2143,
  976,
  2986,
  3050,
  3943,
  3949,
  26,
  2109,
  1998,
  2628],
 [3710,
  241,
  1724,
  4932,
  1749,
  3828,
  1566,
  410,
  4013,
  4061,
  1749,
  722,
  1615,
  4837,
  1749,
  2637,
  3782,
  725,
  2628],
 [2164,
  3943,
  161,
  3485,
  657,
  4146,
  3231,
  4279,
  1749,
  1599,
  4565,
  2449,
  1879,
  797,
  934,
  602,
  829,
  3795,
  3949,
  477,
  1749,
  3660,
  2243,
  2743,
  1749,
  2449,
  3943,
  1286,
  2240,
  2348,
  4044,
  3199,
  2628],
 [2283,
  1876,
  1856,
  2425,
  3450,
  991,
  1386,
  36,
  5199,
  2260,
  4837,
  4146,
  5013,
  4557,
  1749,
  690,
  191,
  2091,
  488,
  1749,
  1076,
  4565,
  4601,
  4193,
  4065,
  2628],
 [1223,
  5143,
  1749,
  745,
  3943,
  1136,
  337,
  257,
  4565,
  2562,
  4731,
  4203,
  2570,
  4837,
  1005,
  949,
  2628],
 [1749,
  2557,
  2541,
  752,
  3052,
  1237,
  1422,
  1749,
  4666,
  4146,
  2348,
  691,
  4393,
  477,
  2994,
  316,
  2628],
 [4146,
  2813,
  3908,
  3082,
  4036,
  5,
  3909,
  477,
  1749,
  4352,
  1446,
  1657,
  4932,
  2348,
  3527,
  1657,
  2628],
 [503,
  1261,
  1778,
  3914,
  2348,
  3478,
  3345,
  1517,
  4932,
  1749,
  1657,
  2879,
  1261,
  1749,
  2164,
  3943,
  4281,
  2628],
 [1749,
  745,
  1940,
  4424,
  5142,
  3007,
  1749,
  3616,
  818,
  2348,
  239,
  55,
  4146,
  1749,
  4412,
  4565,
  1749,
  957,
  3070,
  4146,
  3332,
  2879,
  3283,
  4932,
  2564,
  4837,
  3146,
  2,
  1223,
  1749,
  4529,
  678,
  477,
  2053,
  127,
  4565,
  2213,
  4837,
  1966,
  3813,
  2628],
 [5034,
  5063,
  3665,
  4927,
  3050,
  4217,
  337,
  4110,
  4565,
  1611,
  854,
  1158,
  36,
  991,
  3865,
  3050,
  3943,
  3585,
  1223,
  1749,
  851,
  4146,
  5189,
  2628],
 [2379,
  4146,
  1749,
  634,
  4565,
  1749,
  2138,
  2327,
  1076,
  4013,
  2348,
  562,
  4565,
  544,
  2470,
  2922,
  477,
  979,
  2540,
  1245,
  4679,
  2032,
  5164,
  1749,
  950,
  2628],
 [1749,
  435,
  4565,
  1749,
  3355,
  2509,
  450,
  2812,
  2348,
  1679,
  4565,
  1749,
  1450,
  2670,
  4279,
  1749,
  261,
  1226,
  4146,
  1749,
  1832,
  1448,
  245,
  2628],
 [4936,
  2160,
  4375,
  1749,
  4366,
  2164,
  3943,
  1115,
  45,
  105,
  371,
  36,
  5233,
  4135,
  4279,
  581,
  248,
  2628],
 [2520,
  2497,
  2075,
  3178,
  944,
  3357,
  4837,
  4013,
  3698,
  4565,
  345,
  2411,
  4026,
  4883,
  45,
  2348,
  4906,
  3235,
  3731,
  5012,
  3050,
  4308,
  4026,
  3252,
  4837,
  3148,
  1966,
  4532,
  2791,
  2411,
  944,
  4965,
  1495,
  1330,
  3908,
  4577,
  2628],
 [2348,
  3252,
  1611,
  4878,
  4013,
  2337,
  1875,
  4279,
  5189,
  3943,
  4169,
  4837,
  1749,
  3782,
  4036,
  4153,
  225,
  3949,
  4332,
  74,
  1611,
  1223,
  1517,
  2628],
 [1749,
  4775,
  4565,
  1749,
  5191,
  339,
  3943,
  5019,
  1522,
  936,
  5142,
  1231,
  477,
  2240,
  4146,
  3362,
  545,
  2348,
  962,
  4565,
  1504,
  610,
  4986,
  4146,
  1606,
  3285,
  4146,
  1673,
  3715,
  2628],
 [1749,
  822,
  1937,
  3887,
  1721,
  4565,
  2749,
  4013,
  3433,
  4375,
  2606,
  4932,
  702,
  4565,
  2348,
  3286,
  2190,
  1422,
  1749,
  1500,
  232,
  3670,
  464,
  1223,
  1749,
  2000,
  2628],
 [1749,
  4811,
  4921,
  5220,
  3943,
  1673,
  619,
  2479,
  1778,
  3320,
  442,
  276,
  1280,
  4304,
  3795,
  3702,
  477,
  4026,
  849,
  4279,
  4135,
  2628],
 [2175,
  4874,
  4034,
  477,
  1749,
  1822,
  3943,
  286,
  4837,
  275,
  3587,
  4026,
  2468,
  1280,
  316,
  1424,
  5164,
  2879,
  1386,
  36,
  1749,
  1136,
  3159,
  4874,
  2559,
  5063,
  1590,
  2348,
  2026,
  2628],
 [1749,
  3261,
  1108,
  2254,
  4304,
  5007,
  3949,
  4279,
  2266,
  5110,
  2348,
  3495,
  4279,
  4026,
  3871,
  4146,
  1749,
  1673,
  2511,
  193,
  2628],
 [1749,
  4396,
  311,
  5164,
  3254,
  585,
  4304,
  3943,
  2949,
  3949,
  886,
  868,
  2333,
  3943,
  3086,
  1703,
  3109,
  2971,
  2756,
  3109,
  2628],
 [1749,
  4545,
  496,
  992,
  3681,
  4894,
  477,
  4228,
  3949,
  2753,
  1088,
  1749,
  2968,
  784,
  1834,
  3908,
  4577,
  2628],
 [1749,
  979,
  4633,
  4542,
  784,
  311,
  3240,
  2533,
  4671,
  1749,
  4876,
  4137,
  2503,
  4146,
  4850,
  4742,
  477,
  3698,
  1749,
  2889,
  2628],
 [844,
  1749,
  822,
  2164,
  3943,
  921,
  477,
  1749,
  4262,
  1704,
  4837,
  2348,
  3677,
  4361,
  4146,
  607,
  138,
  275,
  1575,
  976,
  2776,
  4377,
  2628],
 [1749,
  141,
  2859,
  4405,
  3178,
  335,
  589,
  2217,
  239,
  2034,
  1051,
  477,
  3235,
  3670,
  2971,
  2628],
 [1937,
  3887,
  3860,
  2308,
  1575,
  4884,
  1408,
  2254,
  2348,
  836,
  255,
  5142,
  3086,
  3541,
  4837,
  3761,
  3398,
  2155,
  4932,
  498,
  4932,
  2088,
  2628],
 [1749,
  3782,
  3943,
  4193,
  3401,
  5142,
  1650,
  477,
  3553,
  822,
  4380,
  4630,
  2262,
  2148,
  1513,
  4146,
  1749,
  4193,
  757,
  2628],
 [2348,
  2164,
  3943,
  673,
  3050,
  1590,
  1856,
  1808,
  4367,
  2462,
  3050,
  3425,
  4279,
  2425,
  818,
  3898,
  3956,
  5027,
  1223,
  3260,
  3681,
  1769,
  477,
  3029,
  255,
  4443,
  3121,
  976,
  1851,
  2628],
 [1223,
  2348,
  4036,
  2909,
  2670,
  3153,
  3612,
  589,
  3978,
  2348,
  4406,
  4256,
  4146,
  3612,
  2628],
 [1749, 435, 1778, 2258, 1724, 4279, 1749, 1453, 193, 2797, 2628],
 [1538,
  720,
  106,
  4279,
  1767,
  2270,
  1538,
  2237,
  4036,
  4699,
  1541,
  5137,
  1976,
  4297,
  3178,
  1467,
  4770,
  3050,
  5063,
  1580,
  4146,
  1749,
  610,
  2628],
 [2532,
  2943,
  3086,
  2449,
  2006,
  4837,
  1547,
  1749,
  161,
  2254,
  5143,
  3810,
  2532,
  5142,
  4433,
  728,
  2631,
  4066,
  4394,
  2628],
 [2753,
  728,
  5063,
  1223,
  1749,
  4552,
  5142,
  2753,
  728,
  720,
  3729,
  4211,
  614,
  5164,
  3528,
  3956,
  3453,
  2628],
 [1749,
  678,
  3943,
  4190,
  2237,
  1484,
  5058,
  13,
  36,
  5063,
  477,
  5040,
  976,
  1749,
  3880,
  3943,
  395,
  1221,
  3943,
  3252,
  4837,
  4230,
  1412,
  276,
  477,
  171,
  3450,
  249,
  2628],
 [18,
  1596,
  4917,
  976,
  1749,
  4903,
  4170,
  4837,
  3253,
  602,
  2768,
  3863,
  576,
  4146,
  3880,
  2628],
 [2381,
  4146,
  1749,
  3782,
  3943,
  4733,
  1849,
  3887,
  3938,
  3681,
  2534,
  2753,
  4036,
  1989,
  1223,
  2348,
  2859,
  4936,
  822,
  4630,
  2628],
 [657,
  4652,
  477,
  4247,
  1681,
  477,
  2348,
  1673,
  3546,
  2531,
  365,
  3050,
  5096,
  477,
  17,
  668,
  1983,
  3747,
  477,
  1697,
  150,
  4063,
  2304,
  2628],
 [1749,
  794,
  5198,
  1627,
  4013,
  2140,
  4657,
  2272,
  477,
  502,
  2963,
  818,
  3512,
  2807,
  3460,
  4837,
  3219,
  4146,
  4026,
  1343,
  2628],
 [2333,
  3943,
  3086,
  818,
  5208,
  395,
  3066,
  3339,
  1749,
  1433,
  4565,
  3149,
  3327,
  581,
  1749,
  1673,
  3445,
  3859,
  602,
  1023,
  4123,
  4025,
  4565,
  2333,
  2628],
 [1318,
  3736,
  1352,
  4478,
  2537,
  4146,
  1749,
  2164,
  3943,
  351,
  786,
  477,
  3136,
  602,
  1136,
  1994,
  4805,
  4671,
  2601,
  2557,
  4837,
  532,
  1749,
  2097,
  410,
  477,
  1811,
  255,
  477,
  3954,
  589,
  4146,
  1749,
  2898,
  2628],
 [280,
  1141,
  2122,
  150,
  2348,
  1132,
  2473,
  1715,
  4620,
  3050,
  1778,
  9,
  3771,
  4837,
  420,
  1249,
  4565,
  2269,
  4673,
  2628],
 [161,
  3485,
  657,
  4013,
  4242,
  1749,
  2478,
  4615,
  4565,
  1749,
  4487,
  226,
  1641,
  1957,
  702,
  4146,
  2348,
  3935,
  3622,
  2743,
  4405,
  275,
  4671,
  1749,
  2670,
  3914,
  2348,
  722,
  4070,
  2628],
 [4352,
  1000,
  2029,
  2348,
  766,
  4279,
  2791,
  1223,
  1749,
  2594,
  1641,
  3050,
  2096,
  3044,
  4206,
  1621,
  4837,
  5233,
  2348,
  2164,
  3943,
  4207,
  1223,
  189,
  736,
  2628],
 [1749,
  3244,
  4695,
  4565,
  1749,
  2813,
  2289,
  4611,
  3840,
  1132,
  4146,
  1749,
  745,
  4013,
  2337,
  4338,
  4297,
  2776,
  4121,
  2887,
  3472,
  4146,
  1749,
  4207,
  2210,
  4242,
  3235,
  3262,
  3495,
  1223,
  3453,
  2628],
 [3236,
  3943,
  2457,
  5142,
  1016,
  4932,
  1749,
  2080,
  659,
  3070,
  4837,
  4036,
  1769,
  1943,
  4021,
  4279,
  1174,
  4837,
  4921,
  3474,
  477,
  5121,
  1749,
  3343,
  4932,
  498,
  2628],
 [1749,
  4753,
  566,
  1433,
  1296,
  3330,
  3670,
  4279,
  1749,
  3871,
  971,
  3943,
  807,
  1433,
  2348,
  3330,
  2810,
  4837,
  2348,
  5222,
  2628],
 [1749,
  435,
  5164,
  1749,
  4395,
  3160,
  1778,
  3746,
  252,
  477,
  5,
  3717,
  4637,
  255,
  193,
  1296,
  4932,
  3160,
  4013,
  3148,
  5156,
  695,
  4146,
  1749,
  366,
  2628],
 [2044,
  3943,
  3632,
  229,
  4738,
  3050,
  4651,
  4036,
  5,
  3160,
  1736,
  4146,
  1296,
  2454,
  2321,
  2348,
  3725,
  1843,
  3554,
  4013,
  1141,
  1016,
  715,
  2628],
 [3978,
  2348,
  2813,
  3495,
  5017,
  738,
  3050,
  2461,
  2121,
  1749,
  11,
  629,
  2589,
  1715,
  3700,
  2460,
  546,
  3865,
  4081,
  2348,
  3626,
  3558,
  1657,
  2628],
 [3725,
  4121,
  3681,
  2898,
  1673,
  5001,
  4146,
  3450,
  1069,
  150,
  2776,
  4121,
  4146,
  1749,
  2650,
  2628],
 [5220,
  3593,
  2628,
  4146,
  2348,
  1923,
  4565,
  3233,
  4279,
  5039,
  3908,
  4565,
  332,
  1749,
  3262,
  311,
  5164,
  1749,
  246,
  3978,
  3160,
  19,
  602,
  960,
  1521,
  278,
  4060,
  2628],
 [1328,
  4591,
  3943,
  1633,
  3803,
  5,
  2348,
  2463,
  3263,
  477,
  1749,
  1513,
  2057,
  308,
  3943,
  2442,
  4565,
  2773,
  2628],
 [4418,
  3356,
  4837,
  3815,
  326,
  5039,
  1749,
  2458,
  4565,
  1749,
  2164,
  4968,
  3943,
  5019,
  477,
  3036,
  2628],
 [1749,
  2557,
  2541,
  752,
  308,
  3841,
  4837,
  667,
  784,
  4036,
  2707,
  1749,
  1446,
  5004,
  4992,
  4279,
  4026,
  154,
  1223,
  432,
  2930,
  1489,
  2628],
 [2954,
  45,
  2505,
  831,
  4576,
  2254,
  600,
  4237,
  4733,
  788,
  4279,
  4528,
  535,
  1414,
  5063,
  2528,
  2879,
  4311,
  2628],
 [3524,
  35,
  337,
  3476,
  241,
  990,
  1778,
  431,
  4146,
  1749,
  4231,
  481,
  4565,
  3549,
  4159,
  2753,
  4098,
  2337,
  3477,
  602,
  1076,
  2628],
 [1749,
  508,
  1839,
  4146,
  2703,
  4375,
  1749,
  822,
  1136,
  1593,
  3943,
  1647,
  2119,
  4279,
  1749,
  5144,
  3495,
  2628],
 [1749,
  3359,
  2254,
  3160,
  1778,
  481,
  2634,
  3587,
  677,
  3674,
  1749,
  4950,
  1268,
  3050,
  3160,
  461,
  4279,
  602,
  2026,
  4837,
  1778,
  3820,
  37,
  1749,
  264,
  677,
  4790,
  2628],
 [3344,
  4565,
  1749,
  261,
  4977,
  1545,
  1141,
  1749,
  1412,
  5044,
  4840,
  3865,
  1749,
  3782,
  3943,
  2065,
  2333,
  3320,
  3050,
  1502,
  2628],
 [1749,
  167,
  934,
  1837,
  4515,
  3082,
  3943,
  4022,
  477,
  2775,
  420,
  4052,
  1088,
  2333,
  4964,
  4279,
  3082,
  668,
  1847,
  394,
  395,
  849,
  477,
  3951,
  3950,
  2628],
 [1749,
  3407,
  4146,
  3100,
  944,
  420,
  85,
  4037,
  1383,
  4837,
  4303,
  4418,
  2,
  4837,
  3453,
  2411,
  1749,
  2030,
  5148,
  3432,
  2628],
 [1749,
  1748,
  4841,
  185,
  4036,
  3717,
  5,
  2348,
  4301,
  4565,
  1749,
  1499,
  887,
  4512,
  976,
  3735,
  1966,
  1401,
  3110,
  5007,
  2628],
 [4146,
  5132,
  4565,
  1749,
  44,
  3734,
  809,
  3050,
  3655,
  4717,
  2370,
  5125,
  3614,
  4296,
  4935,
  3602,
  395,
  1357,
  1334,
  1538,
  1805,
  4671,
  4573,
  2628],
 [3289,
  3681,
  5004,
  1736,
  4837,
  614,
  5142,
  449,
  477,
  3284,
  4146,
  3066,
  3978,
  1749,
  610,
  5171,
  1749,
  2956,
  1521,
  3943,
  849,
  2628],
 [62,
  3702,
  4146,
  3113,
  4069,
  2237,
  944,
  3472,
  90,
  3840,
  2253,
  5142,
  1071,
  803,
  3631,
  3066,
  4932,
  506,
  4013,
  2337,
  2128,
  2628],
 [1749,
  2542,
  4565,
  1749,
  3815,
  4611,
  3212,
  3334,
  206,
  1749,
  2164,
  2499,
  4206,
  3086,
  3050,
  4433,
  239,
  239,
  2530,
  3803,
  1989,
  3575,
  4671,
  4185,
  2628],
 [2055,
  1641,
  5063,
  532,
  2348,
  3771,
  590,
  477,
  2164,
  3943,
  2521,
  976,
  334,
  980,
  3514,
  696,
  4065,
  2887,
  3928,
  2541,
  2628],
 [2348, 239, 3407, 4308, 1296, 3082, 4146, 2473, 1715, 2879, 4758, 2628],
 [1749,
  2989,
  4213,
  2824,
  1594,
  3383,
  3700,
  2877,
  1422,
  117,
  31,
  2792,
  4146,
  2348,
  2813,
  3612,
  1421,
  477,
  1749,
  4956,
  2628],
 [1749,
  420,
  2029,
  3914,
  2348,
  3252,
  1611,
  4926,
  2210,
  1136,
  3795,
  1422,
  4451,
  1223,
  3612,
  1917,
  2628],
 [1749,
  3100,
  950,
  4044,
  1778,
  491,
  4279,
  3034,
  4565,
  3864,
  3271,
  4942,
  4984,
  477,
  2425,
  818,
  2533,
  1223,
  5236,
  2628],
 [26,
  5142,
  1673,
  980,
  2347,
  1928,
  1749,
  4069,
  305,
  3943,
  337,
  2521,
  3050,
  9,
  4099,
  36,
  3984,
  4837,
  2348,
  5047,
  316,
  1532,
  3050,
  366,
  2155,
  3655,
  36,
  5172,
  2628],
 [1749,
  910,
  3088,
  3978,
  1749,
  657,
  4110,
  2272,
  3050,
  1749,
  2776,
  2012,
  4146,
  4615,
  1010,
  2391,
  4565,
  1045,
  2103,
  737,
  4279,
  3951,
  4146,
  4257,
  2628],
 [1749,
  4932,
  2333,
  1778,
  308,
  2254,
  3160,
  4081,
  1158,
  36,
  1091,
  366,
  5198,
  3961,
  1651,
  4837,
  2742,
  2628],
 [4416,
  4441,
  2254,
  1851,
  3545,
  1749,
  4165,
  4279,
  5156,
  2238,
  4192,
  4837,
  3066,
  76,
  1223,
  757,
  3495,
  2628],
 [139, 279, 4359, 4903, 4098, 182, 982, 2741, 477, 2775, 1749, 1429, 2628],
 [3160,
  3943,
  2903,
  4146,
  4771,
  1294,
  4932,
  2236,
  4932,
  3160,
  1158,
  36,
  2773,
  2628,
  395,
  4771,
  2243,
  1749,
  4975,
  5054,
  2628],
 [1382,
  679,
  2435,
  4112,
  4671,
  1749,
  3903,
  3050,
  370,
  3587,
  4026,
  3041,
  4304,
  2631,
  36,
  4699,
  2440,
  2559,
  5113,
  1382,
  2348,
  1381,
  2928,
  4026,
  4068,
  4430,
  2106,
  4671,
  2032,
  488,
  4146,
  2656,
  4069,
  1782,
  2557,
  2533,
  4837,
  1296,
  172,
  4837,
  3068,
  4026,
  4837,
  4588,
  2493,
  2628],
 [1468,
  3806,
  2741,
  1223,
  4058,
  477,
  3178,
  3978,
  950,
  2336,
  1152,
  4657,
  956,
  5148,
  2644,
  4336,
  3943,
  2774,
  477,
  432,
  2866,
  2582,
  2628],
 [316,
  4146,
  4393,
  2237,
  944,
  1786,
  4013,
  2337,
  1141,
  4146,
  1749,
  4246,
  4565,
  2348,
  1822,
  2753,
  1778,
  1707,
  677,
  3556,
  2628],
 [3651,
  4565,
  5189,
  3943,
  1341,
  4532,
  4169,
  9,
  3655,
  36,
  5063,
  5229,
  1611,
  3978,
  5203,
  1580,
  1749,
  366,
  4757,
  2628],
 [1486,
  1097,
  3050,
  4733,
  3232,
  5142,
  1782,
  4932,
  3145,
  3201,
  2211,
  45,
  663,
  9,
  5203,
  3050,
  5063,
  4308,
  2461,
  589,
  208,
  3082,
  2628],
 [1444,
  2753,
  4751,
  1749,
  2559,
  5113,
  3674,
  4671,
  2032,
  488,
  4146,
  4069,
  3681,
  2495,
  1749,
  3283,
  976,
  2348,
  4260,
  4565,
  2911,
  1940,
  4763,
  4362,
  3030,
  2628],
 [280,
  4837,
  5047,
  4070,
  196,
  1547,
  4565,
  1387,
  1239,
  1223,
  3453,
  1127,
  534,
  3232,
  4837,
  2595,
  980,
  2811,

In [20]:
decoder_input_data=pad_sequences(decoder_input, maxlen=max_len_output, padding='post')
decoder_input_data.shape

(1000, 41)

In [21]:
decoder_target_data=pad_sequences(decoder_target, maxlen=max_len_output, padding='post')
decoder_target_data.shape

(1000, 41)

In [22]:
from tensorflow.keras.utils import to_categorical

decoder_target_data = to_categorical(
    decoder_target_data,
    num_classes=len(unique_words_output)     # same as your output layer vocab size
)
decoder_target_data.shape

(1000, 41, 5239)

In [23]:
import tensorflow as tf
embedding_dim = 16

encoder_embedding = tf.keras.layers.Embedding(input_dim=len(unique_words_input), output_dim=embedding_dim)
decoder_embedding = tf.keras.layers.Embedding(input_dim=len(unique_words_output), output_dim=embedding_dim)

# Get embeddings
enc_inp = encoder_embedding(input_padding)  # shape: (batch, seq_len, 16)
dec_inp = decoder_embedding(decoder_input_data)
print("enc_inp shape:", enc_inp.shape)
print("dec_inp shape:", dec_inp.shape)

enc_inp shape: (1000, 17, 16)
dec_inp shape: (1000, 41, 16)

In [24]:
import tensorflow as tf
from jax.experimental.pallas.ops.gpu.attention_mgpu import attention
from tensorflow.python.ops import array_ops


class Attention:
	"""
	Attention class to implement attntion mentioned in papers:
		https://arxiv.org/abs/1506.03134
		https://arxiv.org/abs/1704.04368
		https://arxiv.org/abs/1508.04025
	"""

	def __init__(self, activation=None, is_decoder_present=False):
		self.activation = activation
		self.is_decoder_present = is_decoder_present

	def attention(
			self,
			encoder_states,
			enc_inp=None,
			decoder_states=None,
			time_major=False,
			return_score=False,
			return_context=False,
			return_alphas=False
			):
		"""
		score(t) = h(s).W.trans(h(t))  dim:[B, T2, T1] = [B, T1, D1].[D1, D2].transpose([B, T2, D2])
		alphas = softmax(t)
		Args:
			:param encoder_states: Encoder outputs on which attention is to be applied, shape: [B, T1, D1]
			:param enc_inp: Encoder inputs, shape: [B, T1, Dim]
			:param decoder_states: Decoder states, shape: [B, T2, D2]
				if None: self attention is implemented with dec_states tf.ones([B, 1, 1])
			:param activation: activation function to apply on score
			:param time_major: Default is False
				True if shape of encoder/decoder is (T, B, D)
				Flase if shape of encoder is (B, T, D)
			:param return_score: Default is False
			:param return_context: Defaults to False
		Returns:
			:return:
				returns outputs([B, T2, D1]) and
				if return_score is True: scores ([B, T2, T1])
				if return_context is True: context ([B, D1])
		"""
		if isinstance(encoder_states, tuple):
			# In case of Bi-RNN, concatenate the forward and the backward RNN outputs.
			encoder_states = tf.concat(encoder_states, 2)

		if time_major:
			# (T,B,D) => (B,T,D)
			encoder_states = tf.transpose(encoder_states, [1, 0, 2])
			decoder_states = tf.transpose(decoder_states, [1, 0, 2])

		batch_size = array_ops.shape(encoder_states)[0]

		if not self.is_decoder_present:
			decoder_states = tf.ones([batch_size, 1, 1], dtype=encoder_states.dtype, name="dec_states")

		encoder_n = encoder_states.shape[2].value  # D1 value - hidden size of the RNN layer encoder
		decoder_n = decoder_states.shape[2].value  # D2 value - hidden size of the RNN layer decoder

		# Trainable parameters
		with tf.variable_scope("attn/attn_weight"):
			w_omega = tf.get_variable(
				name="w_omega", shape=[encoder_n, decoder_n], initializer=tf.random_normal_initializer())  # [D1, D2]

		with tf.variable_scope("attn/score"):
			enc_reshape = tf.reshape(encoder_states, [-1, encoder_n], name="enc_reshape")  # [(B*T1), D1]
			h1 = tf.matmul(enc_reshape, w_omega)  # [(B*T1), D1][D1, D2] = [(B*T1), D2]
			h1_reshape = tf.reshape(h1, tf.stack([batch_size, -1, decoder_n]), name="h1_reshape")  # [B, T1, D2]
			dec_transpose = tf.transpose(decoder_states, [0, 2, 1])  # [B, D2, T2]
			if not self.activation:
				score = tf.matmul(h1_reshape, dec_transpose)  # [B, T1, D2][B, D2, T2] = [B, T1, T2]
			else:
				score = self.activation(tf.matmul(h1_reshape, dec_transpose))  # [B, T1, D2][B, D2, T2] = [B, T1, T2]
			score_transpose = tf.transpose(score, [0, 2, 1])  # [B, T2, T1]

		with tf.variable_scope("attn/align"):
			alphas = tf.nn.softmax(score_transpose, axis=2, name='alphas')  # [B, T2, T1] with softmax on T1

		with tf.variable_scope("attn/outputs"):
			alphas_argmax = tf.argmax(alphas, axis=2, name="outputs_argmax", output_type=tf.int32)  # [B, T2]
			outputs = tf.gather_nd(params=enc_inp, indices=self._index_matrix_to_pairs(alphas_argmax))

		# Output of (Bi-)RNN is reduced with attention vector; the result has (B,D1) shape
		with tf.variable_scope("attn/context_vec"):
			context = tf.reduce_sum(tf.matmul(alphas, encoder_states), axis=1, name="context")   # [B, D1]
		ret = [outputs]
		if return_score:
			ret.append(score_transpose)
		if return_context:
			ret.append(context)
		if return_alphas:
			ret.append(alphas)
		return tuple(ret)

	def _index_matrix_to_pairs(self, index_matrix):
		""" Method to create index to pairs in the first dimension
		[[3,1,2], [2,3,1]] -> [[[0, 3], [1, 1], [2, 2]],
								[[0, 2], [1, 3], [2, 1]]]
		Args:
		:param index_matrix: a Tensor of indexes
		Returns:
		:return Tensor representing the pairwise indexed index_matrix
		"""
		with tf.variable_scope("index_matrix_to_pairs"):
			replicated_first_indices = tf.range(tf.shape(index_matrix)[0])
			rank = len(index_matrix.get_shape())
			if rank == 2:
				replicated_first_indices = tf.tile(
					tf.expand_dims(replicated_first_indices, dim=1),
					[1, tf.shape(index_matrix)[1]])
			return tf.stack([replicated_first_indices, index_matrix], axis=rank)

In [25]:
from tensorflow.keras.layers import Embedding

encoder_embedding = Embedding(input_dim=len(unique_words_input), output_dim=50, mask_zero=True)
decoder_embedding = Embedding(input_dim=len(unique_words_output), output_dim=50, mask_zero=True)

encoder_input_emb = encoder_embedding(input_padding)  # [batch, max_input_len, embedding_dim]
decoder_input_emb = decoder_embedding(decoder_input_data)  # [batch, max_output_len, embedding_dim]

In [43]:
from tensorflow.keras.layers import Dense, Bidirectional
from tensorflow.keras.models import Sequential

dimensions=60
model=Sequential()
model.add(Embedding(len(unique_words_input),dimensions))
model.add(Bidirectional(LSTM(314)))
model.add(Dense(40,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

ValueError: Unrecognized data type: x=[[ 913 3614 1523 ...    0    0    0]
 [1228 1553 1284 ...    0    0    0]
 [3586  827 3504 ...    0    0    0]
 ...
 [2682  277 1939 ...    0    0    0]
 [1478 2560 3443 ...    0    0    0]
 [2780 1886 2407 ...    0    0    0]] (of type <class 'numpy.ndarray'>)

In [48]:
attention_layer = Attention(is_decoder_present=True)

outputs, scores, context, alphas = attention_layer.attention(
    encoder_states=encoder_outputs_,   # BiLSTM hidden states
    enc_inp=enc_inp,                  # encoder embeddings (for gather_nd)
    decoder_states=dec_inp,   # decoder hidden states
    return_score=True,
    return_context=True,
    return_alphas=True
)

IndexError: tuple index out of range

In [3]:
from attention import Attention  # or wherever your class is

attn = Attention()

In [23]:
# ===== Encoder =====
encoder_inputs = Input(shape=(None,))   # input is a sequence of word indices
x = Embedding(input_dim=len(unique_words_input), output_dim=127, input_length=max_len_input)(encoder_inputs)

# LSTM encoder
encoder_lstm = LSTM(256, return_state=True)  # return_state gives hidden + cell states
encoder_outputs, state_h, state_c = encoder_lstm(x)

# Encoder states (to pass into decoder)
encoder_states = [state_h, state_c]

/home/hammadali08/.local/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [24]:
# ===== Decoder =====
decoder_inputs = Input(shape=(None,))  # target sequence input
decoder_embedding = Embedding(input_dim=len(unique_words_output), output_dim=127, input_length=max_len_output)(decoder_inputs)

# LSTM decoder, initialized with encoder states
decoder_lstm = LSTM(256, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_embedding, initial_state=encoder_states)

In [25]:
# Final dense layer to predict word probabilities
from tensorflow.keras.layers import Dense
decoder_dense = Dense(len(unique_words_output), activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

In [26]:
from tensorflow.keras.models import Model
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [ ]:
model.fit([input_padding, decoder_input_data], decoder_target_data,
          batch_size=664,
          epochs=2,
          validation_split=0.2)