In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [45]:
data=pd.read_csv("/home/hammadali08/Vidoes/CSV file/Salary Data.csv")
data.drop(columns=['Gender','Education Level','Job Title','Age'],inplace=True)
data.fillna(data.mean(),inplace=True)
data

     Years of Experience    Salary
0                    5.0   90000.0
1                    3.0   65000.0
2                   15.0  150000.0
3                    7.0   60000.0
4                   20.0  200000.0
..                   ...       ...
370                  8.0   85000.0
371                 19.0  170000.0
372                  2.0   40000.0
373                  7.0   90000.0
374                 15.0  150000.0

[375 rows x 2 columns]

In [46]:
newdata=data.head(10)
newdata

   Years of Experience    Salary
0                  5.0   90000.0
1                  3.0   65000.0
2                 15.0  150000.0
3                  7.0   60000.0
4                 20.0  200000.0
5                  2.0   55000.0
6                 12.0  120000.0
7                  4.0   80000.0
8                  1.0   45000.0
9                 10.0  110000.0

In [47]:
x=newdata[['Years of Experience']]
y=newdata['Salary']

In [48]:
from sklearn.model_selection import LeavePOut,LeaveOneOut,KFold,StratifiedKFold

In [49]:
lo=LeavePOut(p=3)
for train,test in lo.split(x,y):
    print(train,test)

[3 4 5 6 7 8 9] [0 1 2]
[2 4 5 6 7 8 9] [0 1 3]
[2 3 5 6 7 8 9] [0 1 4]
[2 3 4 6 7 8 9] [0 1 5]
[2 3 4 5 7 8 9] [0 1 6]
[2 3 4 5 6 8 9] [0 1 7]
[2 3 4 5 6 7 9] [0 1 8]
[2 3 4 5 6 7 8] [0 1 9]
[1 4 5 6 7 8 9] [0 2 3]
[1 3 5 6 7 8 9] [0 2 4]
[1 3 4 6 7 8 9] [0 2 5]
[1 3 4 5 7 8 9] [0 2 6]
[1 3 4 5 6 8 9] [0 2 7]
[1 3 4 5 6 7 9] [0 2 8]
[1 3 4 5 6 7 8] [0 2 9]
[1 2 5 6 7 8 9] [0 3 4]
[1 2 4 6 7 8 9] [0 3 5]
[1 2 4 5 7 8 9] [0 3 6]
[1 2 4 5 6 8 9] [0 3 7]
[1 2 4 5 6 7 9] [0 3 8]
[1 2 4 5 6 7 8] [0 3 9]
[1 2 3 6 7 8 9] [0 4 5]
[1 2 3 5 7 8 9] [0 4 6]
[1 2 3 5 6 8 9] [0 4 7]
[1 2 3 5 6 7 9] [0 4 8]
[1 2 3 5 6 7 8] [0 4 9]
[1 2 3 4 7 8 9] [0 5 6]
[1 2 3 4 6 8 9] [0 5 7]
[1 2 3 4 6 7 9] [0 5 8]
[1 2 3 4 6 7 8] [0 5 9]
[1 2 3 4 5 8 9] [0 6 7]
[1 2 3 4 5 7 9] [0 6 8]
[1 2 3 4 5 7 8] [0 6 9]
[1 2 3 4 5 6 9] [0 7 8]
[1 2 3 4 5 6 8] [0 7 9]
[1 2 3 4 5 6 7] [0 8 9]
[0 4 5 6 7 8 9] [1 2 3]
[0 3 5 6 7 8 9] [1 2 4]
[0 3 4 6 7 8 9] [1 2 5]
[0 3 4 5 7 8 9] [1 2 6]
[0 3 4 5 6 8 9] [1 2 7]
[0 3 4 5 6 7 9] [1 2 8]
[0 3 4 5 6 7 8] [1 2 9]
[0 2 5 6 7 8 9] [1 3 4]
[0 2 4 6 7 8 9] [1 3 5]
[0 2 4 5 7 8 9] [1 3 6]
[0 2 4 5 6 8 9] [1 3 7]
[0 2 4 5 6 7 9] [1 3 8]
[0 2 4 5 6 7 8] [1 3 9]
[0 2 3 6 7 8 9] [1 4 5]
[0 2 3 5 7 8 9] [1 4 6]
[0 2 3 5 6 8 9] [1 4 7]
[0 2 3 5 6 7 9] [1 4 8]
[0 2 3 5 6 7 8] [1 4 9]
[0 2 3 4 7 8 9] [1 5 6]
[0 2 3 4 6 8 9] [1 5 7]
[0 2 3 4 6 7 9] [1 5 8]
[0 2 3 4 6 7 8] [1 5 9]
[0 2 3 4 5 8 9] [1 6 7]
[0 2 3 4 5 7 9] [1 6 8]
[0 2 3 4 5 7 8] [1 6 9]
[0 2 3 4 5 6 9] [1 7 8]
[0 2 3 4 5 6 8] [1 7 9]
[0 2 3 4 5 6 7] [1 8 9]
[0 1 5 6 7 8 9] [2 3 4]
[0 1 4 6 7 8 9] [2 3 5]
[0 1 4 5 7 8 9] [2 3 6]
[0 1 4 5 6 8 9] [2 3 7]
[0 1 4 5 6 7 9] [2 3 8]
[0 1 4 5 6 7 8] [2 3 9]
[0 1 3 6 7 8 9] [2 4 5]
[0 1 3 5 7 8 9] [2 4 6]
[0 1 3 5 6 8 9] [2 4 7]
[0 1 3 5 6 7 9] [2 4 8]
[0 1 3 5 6 7 8] [2 4 9]
[0 1 3 4 7 8 9] [2 5 6]
[0 1 3 4 6 8 9] [2 5 7]
[0 1 3 4 6 7 9] [2 5 8]
[0 1 3 4 6 7 8] [2 5 9]
[0 1 3 4 5 8 9] [2 6 7]
[0 1 3 4 5 7 9] [2 6 8]
[0 1 3 4 5 7 8] [2 6 9]
[0 1 3 4 5 6 9] [2 7 8]
[0 1 3 4 5 6 8] [2 7 9]
[0 1 3 4 5 6 7] [2 8 9]
[0 1 2 6 7 8 9] [3 4 5]
[0 1 2 5 7 8 9] [3 4 6]
[0 1 2 5 6 8 9] [3 4 7]
[0 1 2 5 6 7 9] [3 4 8]
[0 1 2 5 6 7 8] [3 4 9]
[0 1 2 4 7 8 9] [3 5 6]
[0 1 2 4 6 8 9] [3 5 7]
[0 1 2 4 6 7 9] [3 5 8]
[0 1 2 4 6 7 8] [3 5 9]
[0 1 2 4 5 8 9] [3 6 7]
[0 1 2 4 5 7 9] [3 6 8]
[0 1 2 4 5 7 8] [3 6 9]
[0 1 2 4 5 6 9] [3 7 8]
[0 1 2 4 5 6 8] [3 7 9]
[0 1 2 4 5 6 7] [3 8 9]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 6 8 9] [4 5 7]
[0 1 2 3 6 7 9] [4 5 8]
[0 1 2 3 6 7 8] [4 5 9]
[0 1 2 3 5 8 9] [4 6 7]
[0 1 2 3 5 7 9] [4 6 8]
[0 1 2 3 5 7 8] [4 6 9]
[0 1 2 3 5 6 9] [4 7 8]
[0 1 2 3 5 6 8] [4 7 9]
[0 1 2 3 5 6 7] [4 8 9]
[0 1 2 3 4 8 9] [5 6 7]
[0 1 2 3 4 7 9] [5 6 8]
[0 1 2 3 4 7 8] [5 6 9]
[0 1 2 3 4 6 9] [5 7 8]
[0 1 2 3 4 6 8] [5 7 9]
[0 1 2 3 4 6 7] [5 8 9]
[0 1 2 3 4 5 9] [6 7 8]
[0 1 2 3 4 5 8] [6 7 9]
[0 1 2 3 4 5 7] [6 8 9]
[0 1 2 3 4 5 6] [7 8 9]

In [50]:
loo=LeaveOneOut()
for train,test in loo.split(x,y):
    print(train,test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]

In [51]:
X=data[['Years of Experience']]
Y=data['Salary']

In [52]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [57]:
p=cross_val_score(LinearRegression(),X,Y,cv=15)
p

array([0.87578678, 0.87144075, 0.72193596, 0.67025335, 0.57160367,
       0.80370825, 0.93082366, 0.93423849, 0.94156944, 0.94017378,
       0.92342607, 0.94357954, 0.9437698 , 0.93173585, 0.93971753])

In [58]:
p.sort()
p

array([0.57160367, 0.67025335, 0.72193596, 0.80370825, 0.87144075,
       0.87578678, 0.92342607, 0.93082366, 0.93173585, 0.93423849,
       0.93971753, 0.94017378, 0.94156944, 0.94357954, 0.9437698 ])